package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;
/* loaded from: classes2.dex */
public final class g5 implements y4 {

    /* renamed from: a  reason: collision with root package name */
    private static final Map f21317a = new HashMap();

    /* renamed from: b  reason: collision with root package name */
    private static final Map f21318b = new HashMap();

    /* renamed from: c  reason: collision with root package name */
    private static final Map f21319c = new HashMap();

    public g5() {
        Map map = f21317a;
        map.put(ft.AGREE_AND_PAY, "Aceptar y pagar");
        map.put(ft.AND_OTHER_FUNDING_SOURCES, "y otro");
        map.put(ft.AUTHENTICATING, "Autenticando");
        map.put(ft.BACK_BUTTON, "Atrás");
        map.put(ft.BACKUP_FUNDING_SOURCE, "Respaldo");
        map.put(ft.CANCEL, "Cancelar");
        map.put(ft.CARDTYPE_AMERICANEXPRESS, "American Express");
        map.put(ft.CARDTYPE_CARTAAURA, "Carta Aura");
        map.put(ft.CARDTYPE_CARTEAURORE, "Carte Aurore");
        map.put(ft.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        map.put(ft.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        map.put(ft.CARDTYPE_COFINOGA, "Cofinoga");
        map.put(ft.CARDTYPE_DELTA, "Delta");
        map.put(ft.CARDTYPE_DISCOVER, "Discover");
        map.put(ft.CARDTYPE_ELECTRON, "Electron");
        map.put(ft.CARDTYPE_JCB, "JCB");
        map.put(ft.CARDTYPE_MAESTRO, "Maestro");
        map.put(ft.CARDTYPE_MASTERCARD, "MasterCard");
        map.put(ft.CARDTYPE_POSTEPAY, "Postepay");
        map.put(ft.CARDTYPE_4ETOILES, "4 étoiles");
        map.put(ft.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        map.put(ft.CARDTYPE_VISA, "Visa");
        map.put(ft.CHANGE_PAYMENT_METHOD, "Cambiar forma de pago");
        map.put(ft.CHECKING_ACCOUNT_FOR_INSTITUTION, "De cheques");
        map.put(ft.CHECKING_DEVICE, "Comprobando este dispositivo…");
        map.put(ft.CLEAR_CREDIT_CARD_INFO, "Borrar los datos de la tarjeta");
        map.put(ft.CONFIRM, "Confirmar");
        map.put(ft.CONFIRM_CLEAR_CREDIT_CARD_INFO, "¿Seguro que desea borrar los datos de su tarjeta?");
        map.put(ft.CONFIRM_CHARGE_CREDIT_CARD, "Cargar en tarjeta");
        map.put(ft.CONFIRM_LOG_OUT, "¿Seguro que desea cerrar la sesión de PayPal?");
        map.put(ft.CONFIRM_SEND_PAYMENT, "Pagar");
        map.put(ft.CONSENT_AGREEMENT_AGREE, "Aceptar");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Fecha de creación de la cuenta");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Estado de la cuenta");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Tipo de cuenta");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Dirección");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Rango de edad");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Fecha de nacimiento");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Dirección de correo electrónico");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Nombre completo");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Sexo");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Idioma");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Idioma");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Teléfono");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Zona horaria");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTES, "Compartir lo siguiente: %s.");
        map.put(ft.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Utilizar One Touch™");
        map.put(ft.CONSENT_AGREEMENT_INTRO, "%s le solicita que usted:");
        map.put(ft.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Comparta las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map.put(ft.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Active la visualización de sus formas de pago para que pueda elegir cuál utilizar.");
        map.put(ft.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Autorice cargos</a> correspondientes a futuras compras en %2$s pagadas con PayPal. Indique a PayPal que pague todos los importes solicitados por %3$s.");
        map.put(ft.CONSENT_AGREEMENT_LOYALTY_CARD, "Le permita agregar y administrar su tarjeta de lealtad en su cartera de PayPal.");
        map.put(ft.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Acepte la <a href='%2$s'>Política de Privacidad</a> y las <a href='%3$s'>Condiciones de Uso</a> de %1$s.");
        map.put(ft.CONSENT_AGREEMENT_REQUEST_MONEY, "Le permita <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map.put(ft.CONSENT_AGREEMENT_SEND_MONEY, "Le permita <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map.put(ft.CONSENT_AGREEMENT_TITLE, "Permiso");
        map.put(ft.EMAIL, "Correo electrónico");
        map.put(ft.ENVIRONMENT_MOCK_DATA, "Datos de prueba");
        map.put(ft.ENVIRONMENT_SANDBOX, "Sandbox");
        map.put(ft.EXPIRES_ON_DATE, "Vence");
        map.put(ft.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map.put(ft.FORGOT_PASSWORD, "¿Ha olvidado su contraseña?");
        map.put(ft.FROM_ACCOUNT, "De");
        map.put(ft.FUTURE_PAYMENT_METHOD_QUESTION, "¿Con qué forma de pago le gustaría hacer los pagos futuros a %1$s?");
        map.put(ft.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Su forma de pago predeterminada se utilizará para realizar futuros pagos con PayPal de este vendedor.</p><p>Para cancelar este acuerdo, inicie sesión en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Mi configuración</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio de la lista.</p><p>Aplicará el artículo Pagos recurrentes de las <a href='%s'>Condiciones de Uso de PayPal</a>.</p><p>Para garantizar que los pagos con su cuenta PayPal funcionen correctamente, esta aplicación puede simular una pequeña transacción de prueba, pero no se transferirá dinero.</p>");
        map.put(ft.INTERNAL_ERROR, "Error interno");
        map.put(ft.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Al hacer clic en el botón a continuación, por el presente documento acepto los términos de las <a href='%1$s'>Condiciones de Uso de PayPal</a> y declaro que cumplo las leyes y normas japonesas, incluidas las sanciones contra pagos a Corea del Norte e Irán de conformidad con la <a href='%2$s'>Ley de divisas y comercio exterior</a> para realizar la transacción.</p>");
        map.put(ft.LOG_IN, "Iniciar sesión");
        map.put(ft.LOG_IN_TO_PAYPAL, "Iniciar sesión con Paypal");
        map.put(ft.LOG_OUT_BUTTON, "Cerrar sesión");
        map.put(ft.LOG_OUT, "Cerrar sesión");
        map.put(ft.OK, "Aceptar");
        map.put(ft.PASSWORD, "Contraseña");
        map.put(ft.PAY_AFTER_DELIVERY, "Pago tras la entrega");
        map.put(ft.PAY_WITH, "Pagar con");
        map.put(ft.PAY_WITH_CARD, "Pagar con tarjeta");
        map.put(ft.PAYPAL_BALANCE, "Saldo PayPal");
        map.put(ft.PAYPAL_CREDIT, "PayPal Credit");
        map.put(ft.PHONE, "Teléfono");
        map.put(ft.PIN, "NIP");
        map.put(ft.PREFERRED_PAYMENT_METHOD, "Forma de pago preferida");
        map.put(ft.PRIVACY, "PayPal protege su <a href='%s'>privacidad</a> y sus datos financieros.");
        map.put(ft.PROCESSING, "Procesando");
        map.put(ft.REMEMBER_CARD, "Recordar tarjeta");
        map.put(ft.REQUEST_MONEY, "Solicitar pago");
        map.put(ft.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a las opciones <strong>Iniciar sesión con PayPal</strong> en la sección de configuración del <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el partner.</p>");
        map.put(ft.SAVINGS_ACCOUNT_FOR_INSTITUTION, "De ahorros");
        map.put(ft.SEND_MONEY, "Enviar un pago");
        map.put(ft.SERVER_PROBLEM, "Hay problema en la comunicación con los servidores de PayPal. Inténtelo de nuevo.");
        map.put(ft.SESSION_EXPIRED_MESSAGE, "Inicie sesión de nuevo en PayPal.");
        map.put(ft.SESSION_EXPIRED_TITLE, "Sesión caducada");
        map.put(ft.SHIPPING_ADDRESS, "Dirección de envío");
        map.put(ft.SIGN_UP, "¿Usuario nuevo de PayPal? Registrarse");
        map.put(ft.STAY_LOGGED_IN, "Mantener abierta la sesión");
        map.put(ft.SYSTEM_ERROR_WITH_CODE, "Error del sistema (%s). Inténtelo de nuevo más tarde.");
        map.put(ft.TRY_AGAIN, "Inténtelo de nuevo");
        map.put(ft.TWO_FA_REQUIRED_ERROR, "No puede iniciar sesión porque la autenticación de dos factores ha sido activada para su cuenta.");
        map.put(ft.TWO_FACTOR_AUTH_TITLE, "Código de seguridad");
        map.put(ft.TWO_FACTOR_AUTH_SUBTITLE, "Enviar mensaje de texto a su teléfono. El código de 6 dígitos que reciba será válido durante 5 minutos.");
        map.put(ft.TWO_FACTOR_AUTH_SENDING_DIALOG, "Enviando mensaje de texto");
        map.put(ft.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Ingrese el código de seguridad de 6 dígitos.");
        map.put(ft.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Su número de celular");
        map.put(ft.TWO_FACTOR_AUTH_SEND_SMS, "Enviar mensaje de texto");
        map.put(ft.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Volver a enviar mensaje de texto");
        map.put(ft.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "No puede iniciar sesión porque la autenticación de dos factores ha sido activada para su cuenta. Visite el sitio web de PayPal para activar su clave de seguridad.");
        map.put(ft.UNAUTHORIZED_DEVICE_MESSAGE, "No se permiten los pagos desde este dispositivo.");
        map.put(ft.UNAUTHORIZED_DEVICE_TITLE, "Dispositivo no autorizado");
        map.put(ft.UNAUTHORIZED_MERCHANT_MESSAGE, "Los pagos a este comercio no se permiten (Id. de cliente no válida).");
        map.put(ft.UNAUTHORIZED_MERCHANT_TITLE, "Comercio no válido");
        map.put(ft.UNEXPECTED_PAYMENT_FLOW, "Hubo surgido un problema al procesar su pago. Inténtelo de nuevo.");
        map.put(ft.UNKNOWN_FUNDING_SOURCE, "Origen no reconocido");
        map.put(ft.WE_ARE_SORRY, "Lo sentimos");
        map.put(ft.YOUR_ORDER, "Su pedido");
        map.put(ft.ANDROID_OS_TOO_OLD, "Este dispositivo no puede comunicarse con PayPal porque esta versión de Android es demasiado antigua. Actualice su versión de Android o inténtelo con un dispositivo más nuevo.");
        map.put(ft.CLEAR_CC_ALERT_TITLE, "¿Eliminar tarjeta?");
        map.put(ft.CONSENT_FAILED_ALERT_TITLE, "Error en el permiso");
        map.put(ft.CONNECTION_FAILED_TITLE, "Error de conexión");
        map.put(ft.LOGIN_FAILED_ALERT_TITLE, "Error de inicio de sesión");
        map.put(ft.LOGIN_WITH_EMAIL, "Iniciar sesión con contraseña");
        map.put(ft.LOGIN_WITH_PHONE, "Iniciar sesión con NIP");
        map.put(ft.ONE_MOMENT, "Un momento…");
        map.put(ft.PAY_FAILED_ALERT_TITLE, "Pago fallido");
        map.put(ft.SCAN_CARD_ICON_DESCRIPTION, "Escanear");
        map.put(ft.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Código de seguridad incorrecto. Inténtelo de nuevo.");
        map.put(ft.VIA_LABEL, "Vía");
        map.put(ft.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Error del sistema. Inténtelo de nuevo más tarde.");
        Map map2 = f21318b;
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Comparta información acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Comparta la información acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Comparta información acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Comparta información acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Comparta información acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Comparta con ellos la información acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Comparta las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Comparta las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Comparta la información acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Comparta información acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Comparta la información acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Comparta información acerca de las <a href='%1$s'>formas de pago</a> asociadas a su cuenta PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Comparta las <a href='%1$s'>formas de pago</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Autorice cargos</a> correspondientes a futuras compras en %2$s pagadas con PayPal. Indique a PayPal que pague todos los importes solicitados por %3$s.</p><p>Consulte los <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Pagos recurrentes de PayPal y el Acuerdo de pagos</a> para obtener más información.</p>");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Autorice cargos</a> correspondientes a futuras compras en %2$s pagadas con PayPal. Indique a PayPal que pague todos los importes solicitados por %3$s.</p><p>Consulte los <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Pagos recurrentes de PayPal y el Acuerdo de pagos</a> para obtener más información.</p>");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Autorice cargos</a> para compras futuras realizadas con PayPal. Autorice y ordene a PayPal que pague todos los importes.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Autorice cargos</a> para compras futuras realizadas con PayPal. Autorice y ordene a PayPal que pague todos los importes.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Autorice cargos</a> para compras futuras realizadas con PayPal. Autorice y ordene a PayPal que pague todos los importes.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Preapruebe pagos futuros realizados desde su cuenta PayPal sin tener que identificarse en PayPal cada vez. <a href='%1$s'>Consulte las condiciones adicionales</a>, incluidas las formas de pago y cómo cancelar pagos futuros.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Le permita a %2$s <a href='%1$s'>solicitar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Le permita a %2$s <a href='%1$s'>enviar pagos</a> en su nombre hasta que usted retire dicho permiso.");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte información sobre qué formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte información sobre qué formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte información sobre qué formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Formas de pago</strong></h1><p>PayPal solo comparte las formas de pago que están disponibles para su utilización.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Para garantizar que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicación podría simular una pequeña transacción de prueba, pero no se transferirá dinero alguno.</p><p>Su forma de pago predeterminada (su saldo PayPal, cuenta bancaria asociada, tarjeta de débito o tarjeta de crédito, en ese orden) se utilizará para pagar sus compras de PayPal. Tenga en cuenta que si su forma de pago predeterminada no tiene suficientes fondos para cubrir la compra, su banco o el proveedor de su tarjeta podrían cobrarle una comisión.</p><p>Para cancelar este acuerdo, inicie sesión en su cuenta PayPal y vaya a <strong>Perfil</strong>, luego haga clic en <strong>Mi configuración</strong> y <strong>Cambiar</strong> junto a Iniciar sesión con PayPal.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Para garantizar que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicación podría simular una pequeña transacción de prueba, pero no se transferirá dinero alguno.</p><p>Su saldo PayPal o tarjeta de débito o crédito principal se utilizarán para pagar sus compras de PayPal.</p><p>Para cancelar este acuerdo, inicie sesión en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Mi configuración</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio de la lista.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Para garantizar que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicación podría simular una pequeña transacción de prueba, pero no se transferirá pago alguno.</p><p>Su forma de pago predeterminada se utilizará para pagar las compras de PayPal.</p><p>Para cancelar este acuerdo, inicie sesión en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuración</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio de la lista.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Su forma de pago predeterminada se utilizará para realizar futuros pagos con PayPal de este vendedor.</p><p>Para cancelar este acuerdo, inicie sesión en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Mi configuración</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio de la lista.</p><p>Aplicará el artículo Pagos recurrentes de las <a href='%s'>Condiciones de Uso de PayPal</a>.</p><p>Para garantizar que los pagos con su cuenta PayPal funcionen correctamente, esta aplicación puede simular una pequeña transacción de prueba, pero no se transferirá dinero.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Autorización de pago futuro</strong></h1><p>Para garantizar que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicación podría simular una pequeña transacción de prueba, pero no se transferirá pago alguno.</p><p>Su forma de pago predeterminada se utilizará para pagar las compras de PayPal.</p><p>Para cancelar esta autorización, inicie sesión en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuración de mi cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio de la lista.</p><p>Consulte la sección “Pagos preaprobados” de las <a href='%s'>Condiciones de Uso de PayPal</a> para obtener más información.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autorización de pago futuro</strong></h1><p>Para garantizar que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicación podría simular una pequeña transacción de prueba, pero no se transferirá pago alguno.</p><p>Su forma de pago predeterminada se utilizará para pagar las compras de PayPal.</p><p>Para cancelar esta autorización, inicie sesión en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuración de mi cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio de la lista.</p><p>Consulte la sección “Pagos preaprobados” de las <a href='%s'>Condiciones de Uso de PayPal</a> para obtener más información.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>Para garantizar que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicación podría simular una pequeña transacción de prueba, pero no se transferirá dinero alguno.</p><p>Su saldo PayPal o tarjeta de débito o crédito principal se utilizarán para pagar sus compras de PayPal.</p><p>Para cancelar este acuerdo, inicie sesión en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Mi configuración</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio de la lista.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Autorización de pago futuro</strong></h1><p>Para garantizar que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicación podría simular una pequeña transacción de prueba, pero no se transferirá pago alguno.</p><p>Su forma de pago predeterminada se utilizará para pagar las compras de PayPal.</p><p>Para cancelar esta autorización, inicie sesión en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuración de mi cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio de la lista.</p><p>Consulte la sección “Pagos preaprobados” de las <a href='%s'>Condiciones de Uso de PayPal</a> para obtener más información.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Autorización de pago futuro</strong></h1><p>Para garantizar que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicación podría simular una pequeña transacción de prueba, pero no se transferirá pago alguno.</p><p>Su forma de pago predeterminada se utilizará para pagar las compras de PayPal.</p><p>Para cancelar esta autorización, inicie sesión en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuración de mi cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio de la lista.</p><p>Consulte la sección “Pagos preaprobados” de las <a href='%s'>Condiciones de Uso de PayPal</a> para obtener más información.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Autorización de pago futuro</strong></h1><p>Para garantizar que se puedan hacer cargos en su cuenta PayPal en el futuro, esta aplicación podría simular una pequeña transacción de prueba, pero no se transferirá pago alguno.</p><p>Su forma de pago predeterminada se utilizará para pagar las compras de PayPal.</p><p>Para cancelar esta autorización, inicie sesión en su cuenta PayPal, vaya a <strong>Perfil</strong> &gt; <strong>Configuración de mi cuenta</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio de la lista.</p><p>Consulte la sección “Pagos preaprobados” de las <a href='%s'>Condiciones de Uso de PayPal</a> para obtener más información.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Acuerdo de pago futuro</strong></h1><p>PayPal utilizará primero el saldo de su cuenta PayPal para pagar su compra. Si el saldo no cubre el total, se utilizarán las siguientes formas de pago en este orden: cuenta bancaria, PayPal Credit, tarjeta de débito, tarjeta de crédito y/o eCheck.</p><p>Para cancelar este acuerdo, vaya a www.paypal.com <strong>Perfil</strong> &gt; <strong>Mi configuración</strong> &gt; <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio de la lista.</p><p>Se puede requerir la autorización de un pequeño pago para garantizar que se puedan hacer cargos en su cuenta PayPal en el futuro. La autorización se anulará y no se le realizará ningún cargo.</p>");
        map2.put("LOG_IN_TO_PAYPAL|AU", "Iniciar sesión con Paypal");
        map2.put("LOG_IN_TO_PAYPAL|GB", "Iniciar sesión con Paypal");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el partner.</p><p>Para retirar el permiso, inicie sesión en su cuenta PayPal y haga clic en el icono del engrane. Vaya a <strong>Seguridad</strong>, seleccione <strong>Iniciar sesión con PayPal</strong> y elimine a este partner.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el partner.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a las opciones <strong>Iniciar sesión con PayPal</strong> en la sección de configuración del <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el partner.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en su cuenta PayPal y luego vaya a las opciones <strong>Iniciar sesión con PayPal</strong> en la sección de configuración de su <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el partner.</p><p>Para retirar el permiso, inicie sesión en su cuenta PayPal y haga clic en el icono del engrane. Vaya a <strong>Seguridad</strong>, seleccione <strong>Iniciar sesión con PayPal</strong> y elimine a este partner.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el partner.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el partner.</p><p>Para retirar el permiso, inicie sesión en su cuenta PayPal y haga clic en el icono del engrane. Vaya a <strong>Seguridad</strong>, seleccione <strong>Iniciar sesión con PayPal</strong> y elimine a este partner.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el partner.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en su cuenta PayPal y luego vaya a las opciones <strong>Iniciar sesión con PayPal</strong> en la sección de configuración del <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en su cuenta PayPal, haga clic en el icono del engrane situado en el extremo superior derecho de la pantalla, elija <strong>Centro de Seguridad</strong>, seleccione <strong>Iniciar sesión con PayPal</strong> y elimine al comercio. Si todavía está utilizando la versión anterior del sitio web, vaya a <strong>Mi perfil</strong>, seleccione <strong>La configuración de mi cuenta</strong>, luego seleccione <strong>Iniciar sesión con PayPal</strong> y elimine al comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el partner.</p><p>Para retirar el permiso, inicie sesión en su cuenta PayPal, luego, en la configuración de <strong>Perfil</strong> vaya a <strong>Iniciar sesión con PayPal</strong> y elimine a este partner.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el partner.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.it y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en su cuenta PayPal y luego vaya a las opciones <strong>Iniciar sesión con PayPal</strong> en la sección de configuración de su <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en su cuenta PayPal y luego vaya a las opciones <strong>Iniciar sesión con PayPal</strong> en la sección de configuración del <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en su cuenta PayPal y luego vaya a las opciones <strong>Iniciar sesión con PayPal</strong> en la sección de configuración de su <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el partner.</p><p>Para retirar el permiso, inicie sesión en paypal.ru, haga clic en el icono del engrane situado en el extremo superior derecho de la pantalla, elija la pestaña <strong>Seguridad</strong> y en la opción <strong>Iniciar sesión con PayPal</strong> elimine a este partner.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el partner.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en su cuenta PayPal y luego vaya a las opciones <strong>Iniciar sesión con PayPal</strong> en la sección de configuración del <strong>Perfil</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com.tr, haga clic en el icono del engrane situado en el extremo superior derecho de la pantalla, elija la pestaña <strong>Seguridad</strong> y en la opción <strong>Iniciar sesión con PayPal</strong> elimine a este partner.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a las opciones <strong>Iniciar sesión con PayPal</strong> en la sección de configuración del <strong>Perfil</strong> y elimine a este comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Todos los detalles relevantes de la transacción se compartirán con el comercio.</p><p>Para retirar el permiso, inicie sesión en paypal.com y luego vaya a <strong>Perfil</strong>, <strong>Seguridad</strong>; encuentre <strong>Iniciar sesión con PayPal</strong> y elimine a este comercio.</p><p>PayPal no se responsabiliza de ninguna acción o error cometido por el comercio.</p>");
        Map map3 = f21319c;
        map3.put("AMOUNT_MISMATCH", "El importe total de los artículos del carrito no coincide con el importe de la venta.");
        map3.put("AUTHORIZATION_ALREADY_COMPLETED", "Esta autorización ya se ha completado.");
        map3.put("AUTHORIZATION_CANNOT_BE_VOIDED", "La autorización está en un estado que no permite anularse.");
        map3.put("AUTHORIZATION_EXPIRED", "La autorización ha caducado.");
        map3.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "El Id. de la autorización solicitada no existe.");
        map3.put("AUTHORIZATION_VOIDED", "La autorización se ha anulado.");
        map3.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Solo puede volver a aprobar la autorización original; no una nueva autorización.");
        map3.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "No se permite la nueva autorización en el período de tramitación.");
        map3.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "El importe supera el límite permitido.");
        map3.put("CARD_TOKEN_PAYER_MISMATCH", "No puede acceder a la información de la tarjeta guardada.");
        map3.put("CREDIT_CARD_CVV_CHECK_FAILED", "Los datos de la tarjeta no son válidos. Corrija los datos y envíe de nuevo.");
        map3.put("CREDIT_CARD_REFUSED", "Tarjeta declinada.");
        map3.put("CURRENCY_MISMATCH", "La divisa de la captura debe ser igual que la divisa de la autorización.");
        map3.put("CURRENCY_NOT_ALLOWED", "Esta divisa no es compatible actualmente con PayPal.");
        map3.put("DATA_RETRIEVAL", "Error del sistema. Inténtelo de nuevo más tarde.");
        map3.put("DUPLICATE_REQUEST_ID", "Error del sistema. Inténtelo de nuevo más tarde.");
        map3.put("EXPIRED_CREDIT_CARD", "La tarjeta ha vencido");
        map3.put("EXPIRED_CREDIT_CARD_TOKEN", "Los datos de esta tarjeta ya no están registrados.\nEnvíelos nuevamente.");
        map3.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Función no disponible para este vendedor.");
        map3.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Esta transacción se ha reembolsado parcialmente.");
        map3.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Pago inmediato no compatible con la finalidad transmitida.");
        map3.put("INSTRUMENT_DECLINED", "No se ha aceptado la forma de pago seleccionada. Seleccione otra forma de pago.");
        map3.put("INSUFFICIENT_FUNDS", "El comprador no puede pagar porque no tiene suficiente saldo.");
        map3.put("INTERNAL_SERVICE_ERROR", "Error del sistema. Inténtelo de nuevo más tarde.");
        map3.put("INVALID_ACCOUNT_NUMBER", "Ese número de cuenta no existe.");
        map3.put("INVALID_ARGUMENT", "La transacción se ha declinado debido a un argumento no válido");
        map3.put("INVALID_CITY_STATE_ZIP", "Combinación de ciudad/estado/código postal no válida.");
        map3.put("INVALID_FACILITATOR_CONFIGURATION", "Esta transacción no puede procesarse debido a una configuración no válida del facilitador.");
        map3.put("INVALID_PAYER_ID", "Error del sistema (la id. del pagador no es válida). Inténtelo de nuevo más tarde.");
        map3.put("INVALID_RESOURCE_ID", "Error del sistema. Inténtelo de nuevo más tarde.");
        map3.put("PAYEE_ACCOUNT_INVALID", "La cuenta del proveedor no tiene un correo electrónico confirmado.");
        map3.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Este proveedor no puede recibir pagos por el momento.");
        map3.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "La cuenta del proveedor no tiene un correo electrónico confirmado.");
        map3.put("PAYEE_ACCOUNT_RESTRICTED", "Este proveedor no puede recibir pagos por el momento.");
        map3.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Su cuenta está bloqueada o cerrada.");
        map3.put("PAYER_ACCOUNT_RESTRICTED", "Su cuenta está limitada.");
        map3.put("PAYER_CANNOT_PAY", "No puede pagar esta transacción con PayPal.");
        map3.put("PAYER_EMPTY_BILLING_ADDRESS", "La dirección de facturación es obligatoria para las transacciones con tarjetas de crédito que no sean de PayPal.");
        map3.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "No puede acceder a la información de la tarjeta guardada.");
        map3.put("PAYMENT_APPROVAL_EXPIRED", "La aprobación del pago ha vencido.");
        map3.put("PAYMENT_EXPIRED", "El pago ha vencido.");
        map3.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "El pagador no ha aprobado el pago.");
        map3.put("PAYMENT_REQUEST_ID_INVALID", "La Id. de la solicitud de PayPal no es válido. Inténtelo de nuevo más tarde.");
        map3.put("PAYMENT_STATE_INVALID", "Esta solicitud no es válida debido al estado actual del pago.");
        map3.put("PERMISSION_DENIED", "No hay permiso para la operación solicitada.");
        map3.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "El reembolso solicitado supera el importe de la transacción original.");
        map3.put("REFUND_TIME_LIMIT_EXCEEDED", "Esta transacción es muy antigua para reembolsarse.");
        map3.put("REQUIRED_SCOPE_MISSING", "Error del sistema. Inténtelo de nuevo más tarde.");
        map3.put("TOO_MANY_REAUTHORIZATIONS", "No se permiten nuevas autorizaciones para esta autorización.");
        map3.put("TRANSACTION_ALREADY_REFUNDED", "El importe de esta transacción ya se ha reembolsado.");
        map3.put("TRANSACTION_LIMIT_EXCEEDED", "El importe supera el límite permitido.");
        map3.put("TRANSACTION_REFUSED", "La transacción se ha declinado.");
        map3.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "La transacción se ha declinado.");
        map3.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Hay una preferencia de perfil definida para rechazar automáticamente todas las transacciones.");
        map3.put("UNKNOWN_ERROR", "Error del sistema. Inténtelo de nuevo más tarde.");
        map3.put("UNSUPPORTED_PAYEE_COUNTRY", "No disponible en su país.");
        map3.put("VALIDATION_ERROR", "La información de pago no es válida. Corrija los datos y envíe de nuevo.");
        map3.put("ORDER_ALREADY_COMPLETED", "El pedido ya se ha anulado, ha caducado o se ha completado.");
        map3.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Se ha llegado al número máximo de autorizaciones permitidas para el pedido.");
        map3.put("ORDER_VOIDED", "El pedido se ha anulado.");
        map3.put("ORDER_CANNOT_BE_VOIDED", "El pedido está en un estado que evita que pueda anularse.");
        map3.put("INVALID_EXPERIENCE_PROFILE_ID", "Error del sistema. Inténtelo de nuevo más tarde.");
        map3.put("UNAUTHORIZED_PAYMENT", "El comercio no acepta este tipo de pagos.");
        map3.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Divisa no compatible para el tipo de tarjeta.");
        map3.put("DCC_CC_TYPE_NOT_SUPPORTED", "Tipo de tarjeta no compatible.");
        map3.put("ADDRESS_ADDITION_ERROR", "Error encontrado al agregar dirección de envío a cuenta PayPal.");
        map3.put("DUPLICATE_TRANSACTION", "Transacción duplicada.");
        map3.put("INVALID_SHIPPING_ADDRESS", "La dirección de envío proporcionada no es válida.");
        map3.put("PAYMENT_CREATION_ERROR", "Se ha producido un problema al configurar este pago. Visite el sitio web de PayPal para revisar su cuenta.");
        map3.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Se ha producido un problema al configurar este pago: su tarjeta ha vencido. Visite el sitio web de PayPal para revisar su cuenta.");
        map3.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Se ha producido un problema al configurar este pago: se requiere un pago instantáneo, como una tarjeta de crédito. Visite el sitio web de PayPal para revisar su cuenta.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Se ha producido un problema al configurar este pago: la tarjeta debe estar confirmada. Visite el sitio web de PayPal para revisar su cuenta.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Se ha producido un problema al configurar este pago: esta aplicación requiere que su cuenta incluya un número de teléfono. Visite el sitio web de PayPal para revisar su cuenta.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Se ha producido un problema al configurar este pago: la cuenta necesita una forma de pago válida, como una cuenta bancaria o tarjeta de pago. Visite el sitio web de PayPal para revisar su cuenta.");
        map3.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Se ha producido un problema al configurar este pago: su saldo es negativo. Visite el sitio web de PayPal para revisar su cuenta.");
        map3.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Se ha producido un problema al configurar este pago: ha alcanzado su límite de envío. Visite el sitio web de PayPal para revisar su cuenta.");
        map3.put("AUTH_RC_RISK_FAILURE", "Declinado debido a riesgo.");
        map3.put("AUTH_RC_OFAC_BLOCKED_IP", "Cliente no autorizado.");
        map3.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Cliente no autorizado.");
        map3.put("invalid_user", "Nombre de usuario o contraseña incorrectos. Inténtelo de nuevo.");
        map3.put("locked_user", "Su cuenta PayPal ha sido bloqueada temporalmente. Inténtelo de nuevo más tarde o visite www.paypal.com para desbloquear inmediatamente su cuenta PayPal.");
        map3.put("max_attempts_exceeded", "Demasiados intentos fallidos de inicio de sesión. Inténtelo de nuevo más tarde.");
        map3.put("invalid_request", "Se ha producido un error.");
        map3.put("unauthorized_client", "Solicitud no autorizada.");
        map3.put("access_denied", "Solicitud no autorizada.");
        map3.put("unsupported_response_type", "Se ha producido un error.");
        map3.put("invalid_scope", "Solicitud no autorizada.");
        map3.put("server_error", "Error del sistema. Inténtelo de nuevo más tarde.");
        map3.put("temporarily_unavailable", "Error del sistema. Inténtelo de nuevo más tarde.");
        map3.put("stepup_required", "El inicio de sesión no se puede completar en este momento. Inténtelo de nuevo más tarde o visite www.paypal.com para tratar cualquier problema de seguridad relacionado con su cuenta PayPal.");
        map3.put("account_locked_generate_challenge_limit_exceeded", "Demasiados intentos de inicio de sesión. Inténtelo de nuevo más tarde o comuníquese con PayPal para obtener ayuda.");
    }

    @Override // com.paypal.android.sdk.y4
    public final String a() {
        return "es_MX";
    }

    @Override // com.paypal.android.sdk.y4
    public final /* synthetic */ String a(Enum r32, String str) {
        ft ftVar = (ft) r32;
        String str2 = ftVar.toString() + "|" + str;
        Map map = f21318b;
        return (String) (map.containsKey(str2) ? map.get(str2) : f21317a.get(ftVar));
    }

    @Override // com.paypal.android.sdk.y4
    public final String a(String str) {
        return (String) f21319c.get(str);
    }
}
