package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;
/* loaded from: classes2.dex */
public final class i5 implements y4 {

    /* renamed from: a  reason: collision with root package name */
    private static final Map f21379a = new HashMap();

    /* renamed from: b  reason: collision with root package name */
    private static final Map f21380b = new HashMap();

    /* renamed from: c  reason: collision with root package name */
    private static final Map f21381c = new HashMap();

    public i5() {
        Map map = f21379a;
        map.put(ft.AGREE_AND_PAY, "הסכם ושלם");
        map.put(ft.AND_OTHER_FUNDING_SOURCES, "ואחרים");
        map.put(ft.AUTHENTICATING, "אימות");
        map.put(ft.BACK_BUTTON, "חזרה");
        map.put(ft.BACKUP_FUNDING_SOURCE, "גיבוי");
        map.put(ft.CANCEL, "ביטול");
        map.put(ft.CARDTYPE_AMERICANEXPRESS, "אמריקן אקספרס");
        map.put(ft.CARDTYPE_CARTAAURA, "Carta Aura\u200f");
        map.put(ft.CARDTYPE_CARTEAURORE, "Carte Aurore\u200f");
        map.put(ft.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal\u200f");
        map.put(ft.CARDTYPE_CARTEBLEUE, "Carte Bancaire\u200f");
        map.put(ft.CARDTYPE_COFINOGA, "Cofinoga\u200f");
        map.put(ft.CARDTYPE_DELTA, "Delta\u200f");
        map.put(ft.CARDTYPE_DISCOVER, "Discover\u200f");
        map.put(ft.CARDTYPE_ELECTRON, "Electron\u200f");
        map.put(ft.CARDTYPE_JCB, "JCB\u200f");
        map.put(ft.CARDTYPE_MAESTRO, "Maestro\u200f");
        map.put(ft.CARDTYPE_MASTERCARD, "מאסטרקארד");
        map.put(ft.CARDTYPE_POSTEPAY, "Postepay\u200f");
        map.put(ft.CARDTYPE_4ETOILES, "\u200e4 étoiles\u200e\u200f");
        map.put(ft.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora\u200f");
        map.put(ft.CARDTYPE_VISA, "ויזה");
        map.put(ft.CHANGE_PAYMENT_METHOD, "שנה שיטת תשלום");
        map.put(ft.CHECKING_ACCOUNT_FOR_INSTITUTION, "עו״ש");
        map.put(ft.CHECKING_DEVICE, "בודק מכשיר זה…");
        map.put(ft.CLEAR_CREDIT_CARD_INFO, "נקה פרטי כרטיס");
        map.put(ft.CONFIRM, "אשר");
        map.put(ft.CONFIRM_CLEAR_CREDIT_CARD_INFO, "האם אתה בטוח שאתה רוצה להסיר את פרטי הכרטיס שלך?");
        map.put(ft.CONFIRM_CHARGE_CREDIT_CARD, "חייב כרטיס");
        map.put(ft.CONFIRM_LOG_OUT, "האם אתה בטוח שאתה רוצה לצאת מ-PayPal\u200f?");
        map.put(ft.CONFIRM_SEND_PAYMENT, "שלם");
        map.put(ft.CONSENT_AGREEMENT_AGREE, "מסכים");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "תאריך פתיחת החשבון");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "מצב חשבון");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "סוג חשבון");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "כתובת");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "טווח גילים");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "תאריך לידה");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "כתובת אימייל");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "שם מלא");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "מין");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "שפה");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "אזור");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "טלפון");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "אזור זמן");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTES, "שתף את הפרטים הבאים: \u200e%s\u200f.");
        map.put(ft.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "השתמש ב-Express Checkout\u200f.");
        map.put(ft.CONSENT_AGREEMENT_INTRO, "%s מבקש כי:");
        map.put(ft.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "שתף את <a href='%1$s'>שיטות התשלום</a> המקושרות לחשבון ה-PayPal שלך.");
        map.put(ft.CONSENT_AGREEMENT_FUNDING_OPTIONS, "הפעל תצוגה של האפשרויות הכספיות שלך שתאפשר לך לבחור.");
        map.put(ft.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>אשר חיובים</a> עבור קניות עתידיות אצל \u200e%2$s באמצעות PayPal\u200f. הורית ל-PayPal לשלם את כל הסכומים ש-\u200e%3$s מבקש.");
        map.put(ft.CONSENT_AGREEMENT_LOYALTY_CARD, "תאפשר לו להוסיף ולנהל את כרטיס המועדון שלו ב‘ארנק‘ שבחשבון ה-PayPal שלך.");
        map.put(ft.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "תסכים ל<a href='%2$s'>מדיניות הפרטיות</a> ו<a href='%3$s'>הסכם המשתמש</a> של %1$s\u200f.");
        map.put(ft.CONSENT_AGREEMENT_REQUEST_MONEY, "תאפשר לו <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map.put(ft.CONSENT_AGREEMENT_SEND_MONEY, "תאפשר לו <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map.put(ft.CONSENT_AGREEMENT_TITLE, "הסכמה");
        map.put(ft.EMAIL, "אימייל");
        map.put(ft.ENVIRONMENT_MOCK_DATA, "פרטים מדומים");
        map.put(ft.ENVIRONMENT_SANDBOX, "\u200fSandbox");
        map.put(ft.EXPIRES_ON_DATE, "תאריך תפוגה");
        map.put(ft.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>דרכי תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו משיטות התשלום שלך זמינות לשימוש.</p>");
        map.put(ft.FORGOT_PASSWORD, "שכחת את הסיסמה?");
        map.put(ft.FROM_ACCOUNT, "מ-");
        map.put(ft.FUTURE_PAYMENT_METHOD_QUESTION, "כיצד תרצה לשלם עבור תשלומים עתידיים ל-%1$s\u200f?");
        map.put(ft.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>הסכם תשלום עתידי</strong></h1><p>ברירת המחדל לשיטת התשלום שלך תשמש עבור תשלומים עתידיים באמצעות PayPal אצל בעל עסק זה.</p><p>כדי לבטל הסכם זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>ההגדרות שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>המקטע ‘הוראת קבע‘ של <a href='%s'>הסכם המשתמש של PayPal</a> יחול.</p><p>כדי לוודא שהתשלומים שלך יעבדו עם חשבון ה-PayPal שלך, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר כסף.</p>");
        map.put(ft.INTERNAL_ERROR, "שגיאה פנימית");
        map.put(ft.JAPANESE_COMPLIANCE_AGREEMENT, "<p>על-ידי לחיצה על הלחצן למטה, אני מסכים בזאת לתנאי <a href='%1$s'>הסכם המשתמש של PayPal</a> ומצהיר שאני פועל בהתאם לחוקים ולתקנות ביפן, כולל סנקציות נגד תשלום לצפון קוריאה ואירן, בהתאם ל-<a href='%2$s'>Foreign Exchange and Foreign Trade Act</a>, להשלמת העסקה.</p>");
        map.put(ft.LOG_IN, "כניסה");
        map.put(ft.LOG_IN_TO_PAYPAL, "היכנס עם PayPal\u200f");
        map.put(ft.LOG_OUT_BUTTON, "יציאה");
        map.put(ft.LOG_OUT, "יציאה");
        map.put(ft.OK, "אישור");
        map.put(ft.PASSWORD, "סיסמה");
        map.put(ft.PAY_AFTER_DELIVERY, "שלם לאחר המסירה");
        map.put(ft.PAY_WITH, "שלם באמצעות");
        map.put(ft.PAY_WITH_CARD, "שלם באמצעות כרטיס");
        map.put(ft.PAYPAL_BALANCE, "יתרת חשבון ה-PayPal");
        map.put(ft.PAYPAL_CREDIT, "PayPal Credit");
        map.put(ft.PHONE, "טלפון");
        map.put(ft.PIN, "קוד סודי");
        map.put(ft.PREFERRED_PAYMENT_METHOD, "שיטת תשלום מועדפת");
        map.put(ft.PRIVACY, "PayPal מגינה על ה<a href='%s'>פרטיות</a> והמידע הפיננסי שלך.");
        map.put(ft.PROCESSING, "עיבוד");
        map.put(ft.REMEMBER_CARD, "זכור כרטיס");
        map.put(ft.REQUEST_MONEY, "בקש תשלום");
        map.put(ft.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        map.put(ft.SAVINGS_ACCOUNT_FOR_INSTITUTION, "חיסכון");
        map.put(ft.SEND_MONEY, "שלח תשלום");
        map.put(ft.SERVER_PROBLEM, "הייתה בעיה ביצירת קשר עם השרתים של PayPal\u200f. נסה שוב.");
        map.put(ft.SESSION_EXPIRED_MESSAGE, "היכנס שוב ל-PayPal\u200f.");
        map.put(ft.SESSION_EXPIRED_TITLE, "פג תוקף ההפעלה");
        map.put(ft.SHIPPING_ADDRESS, "כתובת למשלוח");
        map.put(ft.SIGN_UP, "חדש ב-PayPal\u200f? הירשם");
        map.put(ft.STAY_LOGGED_IN, "הישאר מחובר");
        map.put(ft.SYSTEM_ERROR_WITH_CODE, "שגיאת מערכת (%s\u200f). נסה שוב מאוחר יותר.");
        map.put(ft.TRY_AGAIN, "נסה שוב");
        map.put(ft.TWO_FA_REQUIRED_ERROR, "לא ניתן להיכנס לחשבון, משום שאימות בשני שלבים הופעל עבור החשבון שלך.");
        map.put(ft.TWO_FACTOR_AUTH_TITLE, "קוד אבטחה");
        map.put(ft.TWO_FACTOR_AUTH_SUBTITLE, "שלח הודעת טקסט לטלפון שלך. הקוד בן שש הספרות שתקבל יישאר בתוקף למשך 5 דקות.");
        map.put(ft.TWO_FACTOR_AUTH_SENDING_DIALOG, "שולח טקסט");
        map.put(ft.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "הזן את קוד האבטחה בן שש הספרות");
        map.put(ft.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "מספר הטלפון הנייד שלך");
        map.put(ft.TWO_FACTOR_AUTH_SEND_SMS, "שלח טקסט");
        map.put(ft.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "שלח טקסט שוב");
        map.put(ft.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "לא ניתן להיכנס לחשבון, משום שאימות בשני שלבים הופעל עבור החשבון שלך. בקר באתר PayPal כדי להפעיל את מפתח האבטחה שלך.");
        map.put(ft.UNAUTHORIZED_DEVICE_MESSAGE, "לא ניתן לשלם ממכשיר זה.");
        map.put(ft.UNAUTHORIZED_DEVICE_TITLE, "מכשיר בלתי-מורשה");
        map.put(ft.UNAUTHORIZED_MERCHANT_MESSAGE, "לא ניתן לשלם לבעל עסק זה (מזהה לקוח בלתי-חוקי).");
        map.put(ft.UNAUTHORIZED_MERCHANT_TITLE, "בעל עסק בלתי-חוקי");
        map.put(ft.UNEXPECTED_PAYMENT_FLOW, "אירעה בעיה בעיבוד התשלום שלך. נסה שוב.");
        map.put(ft.UNKNOWN_FUNDING_SOURCE, "מקור בלתי מזוהה");
        map.put(ft.WE_ARE_SORRY, "מצטערים");
        map.put(ft.YOUR_ORDER, "ההזמנה שלך");
        map.put(ft.ANDROID_OS_TOO_OLD, "מכשיר זה לא יכול ליצור קשר עם PayPal משום שגירסה זו של אנדרואיד ישנה מדי. שדרג את גירסת האנדרואיד או נסה מכשיר חדש יותר.");
        map.put(ft.CLEAR_CC_ALERT_TITLE, "להסיר את הכרטיס?");
        map.put(ft.CONSENT_FAILED_ALERT_TITLE, "ההסכמה נכשלה");
        map.put(ft.CONNECTION_FAILED_TITLE, "החיבור נכשל");
        map.put(ft.LOGIN_FAILED_ALERT_TITLE, "הכניסה נכשלה");
        map.put(ft.LOGIN_WITH_EMAIL, "היכנס באמצעות סיסמה");
        map.put(ft.LOGIN_WITH_PHONE, "היכנס באמצעות קוד סודי");
        map.put(ft.ONE_MOMENT, "המתן רגע אחד…");
        map.put(ft.PAY_FAILED_ALERT_TITLE, "התשלום נכשל");
        map.put(ft.SCAN_CARD_ICON_DESCRIPTION, "סריקה");
        map.put(ft.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "קוד אבטחה שגוי. נסה שוב.");
        map.put(ft.VIA_LABEL, "באמצעות");
        map.put(ft.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "שגיאת מערכת. נסה שוב מאוחר יותר.");
        Map map2 = f21380b;
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "שתף מידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "שתף את המידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "שתף מידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "שתף מידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "שתף מידע על <a href='%1$s'>שיטות התשלום</a> המקושרות לחשבון ה-PayPal שלך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "שתף איתם מידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "שתף את <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "שתף את <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "שתף את המידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "שתף מידע על <a href='%1$s'>שיטות התשלום</a> המקושרות לחשבון ה-PayPal שלך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "שתף את המידע על <a href='%1$s'>המקורות הכספיים</a> המקושרים לחשבון ה-PayPal שלך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "שתף מידע על <a href='%1$s'>שיטות התשלום</a> המקושרות לחשבון ה-PayPal שלך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "שתף את <a href='%1$s'>המקורות הכספיים</a> מטעמך עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>אשר חיובים</a> עבור קניות עתידיות אצל \u200e%2$s באמצעות PayPal\u200f. הורית ל-PayPal לשלם את כל הסכומים ש-\u200e%3$s מבקש.</p><p>לפרטים נוספים, עיין ב<a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>הסכם הוראות הקבע והחיוב של PayPal\u200f</a>.</p>");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>אשר חיובים</a> עבור קניות עתידיות אצל \u200e%2$s באמצעות PayPal\u200f. הורית ל-PayPal לשלם את כל הסכומים ש-\u200e%3$s מבקש.</p><p>לפרטים נוספים, עיין ב<a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>הסכם הוראות הקבע והחיוב של PayPal\u200f</a>.</p>");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>אשר חיובים</a> עבור קניות עתידיות באמצעות PayPal\u200f. אתה מעניק ל-PayPal אישור לשלם את כל הסכומים.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>אשר חיובים</a> עבור קניות עתידיות באמצעות PayPal\u200f. אתה מעניק ל-PayPal אישור לשלם את כל הסכומים.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>אשר חיובים</a> עבור קניות עתידיות באמצעות PayPal\u200f. אתה מעניק ל-PayPal אישור לשלם את כל הסכומים.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "אשר מראש תשלומים עתידיים מחשבון ה-PayPal שלך בלי להיכנס אל PayPal בכל פעם. <a href='%1$s'>ראה תנאים נוספים</a>, כולל שיטות תשלום וכיצד לבטל תשלומים עתידיים.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לבקש תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "תאפשר ל-\u200e%2$s\u200e <a href='%1$s'>לשלוח תשלום</a> בשמך, עד שתבטל את הסכמתך.");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>שיטות תשלום</strong></h1><p>המידע היחיד ש-PayPal משתפת הוא אילו מהמקורות הכספיים שלך זמינים לשימוש.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>הסכם תשלומים עתידיים</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר כסף.</p><p>ברירת המחדל לשיטת התשלום שלך (יתרת חשבון ה-PayPal שלך, חשבון בנק מקושר או כרטיס אשראי, בסדר הזה) תשמש לתשלום עבור הקניות באמצעות PayPal\u200f. שים לב, אם בברירת המחדל לשיטת התשלום שלך לא יהיה מספיק כסף לכיסוי הקנייה, הבנק שבו מתנהל חשבונך או ספק הכרטיס שלך עשוי לחייב אותך בעמלה.</p><p>כדי לבטל הסכם זה, היכנס לחשבון ה-PayPal שלך ועבור אל <strong>פרופיל</strong>, לאחר מכן לחץ על <strong>ההגדרות שלי</strong> ועל <strong>שינוי</strong> לצד ’היכנס עם PayPal\u200f‘.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>הסכם תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר כסף.</p><p>יתרת חשבון ה-PayPal שלך או כרטיס האשראי הראשי שלך ישמשו לתשלום עבור הקניות באמצעות PayPal\u200f.</p><p>כדי לבטל הסכם זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>ההגדרות שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>הסכם תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר תשלום.</p><p>ברירת המחדל לשיטת התשלום שלך תשמש לתשלום עבור הקניות באמצעות PayPal\u200f.</p><p>כדי לבטל הסכם זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>הגדרות</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>הסכם תשלום עתידי</strong></h1><p>ברירת המחדל לשיטת התשלום שלך תשמש עבור תשלומים עתידיים באמצעות PayPal אצל בעל עסק זה.</p><p>כדי לבטל הסכם זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>ההגדרות שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>המקטע ‘הוראת קבע‘ של <a href='%s'>הסכם המשתמש של PayPal</a> יחול.</p><p>כדי לוודא שהתשלומים שלך יעבדו עם חשבון ה-PayPal שלך, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר כסף.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>אישור תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר תשלום.</p><p>ברירת המחדל לשיטת התשלום שלך תשמש לתשלום עבור הקניות באמצעות PayPal\u200f.</p><p>כדי לבטל אישור זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>הגדרות החשבון שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>לפרטים נוספים, עיין במקטע ’תשלומים שאושרו מראש‘ ב<a href='%s'>הסכם המשתמש של PayPal\u200f</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>אישור תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר תשלום.</p><p>ברירת המחדל לשיטת התשלום שלך תשמש לתשלום עבור הקניות באמצעות PayPal\u200f.</p><p>כדי לבטל אישור זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>הגדרות החשבון שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>לפרטים נוספים, עיין במקטע ’תשלומים שאושרו מראש‘ ב<a href='%s'>הסכם המשתמש של PayPal\u200f</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>הסכם תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר כסף.</p><p>יתרת חשבון ה-PayPal שלך או כרטיס האשראי הראשי שלך ישמשו לתשלום עבור הקניות באמצעות PayPal\u200f.</p><p>כדי לבטל הסכם זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>ההגדרות שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>אישור תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר תשלום.</p><p>ברירת המחדל לשיטת התשלום שלך תשמש לתשלום עבור הקניות באמצעות PayPal\u200f.</p><p>כדי לבטל אישור זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>הגדרות החשבון שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>לפרטים נוספים, עיין במקטע ’תשלומים שאושרו מראש‘ ב<a href='%s'>הסכם המשתמש של PayPal\u200f</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>אישור תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר תשלום.</p><p>ברירת המחדל לשיטת התשלום שלך תשמש לתשלום עבור הקניות באמצעות PayPal\u200f.</p><p>כדי לבטל אישור זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>הגדרות החשבון שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>לפרטים נוספים, עיין במקטע ’תשלומים שאושרו מראש‘ ב<a href='%s'>הסכם המשתמש של PayPal\u200f</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>אישור תשלום עתידי</strong></h1><p>כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד, יישום זה עשוי לבצע הדמיה של עסקה קטנה לצורך בדיקה, אך בפועל לא יועבר תשלום.</p><p>ברירת המחדל לשיטת התשלום שלך תשמש לתשלום עבור הקניות באמצעות PayPal\u200f.</p><p>כדי לבטל אישור זה, היכנס לחשבון ה-PayPal שלך, עבור אל <strong>פרופיל</strong> &gt; <strong>הגדרות החשבון שלי</strong> &gt; <strong>היכנס עם PayPal</strong> והסר בעל עסק זה מהרשימה.</p><p>לפרטים נוספים, עיין במקטע ’תשלומים שאושרו מראש‘ ב<a href='%s'>הסכם המשתמש של PayPal\u200f</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>הסכם תשלום עתידי</strong></h1><p>PayPal תשתמש תחילה ביתרת חשבון ה-PayPal שלך כדי לשלם עבור הקנייה שלך. במקרה שהיתרה אינה מכסה את הסכום המלא, יעשה שימוש בחשבון הבנק, PayPal Credit, כרטיס האשראי ו/או המחאה אלקטרונית שלך, בסדר הזה.</p><p>כדי לבטל הסכם זה, עבור אל www.paypal.co.il <strong>פרופיל</strong> &gt; <strong>ההגדרות שלי</strong> &gt; <strong>היכנס עם PayPal</strong> ולאחר מכן הסר בעל עסק זה מהרשימה.</p><p>ייתכן שיידרש אישור תשלום קטן כדי לוודא שניתן יהיה לחייב את חשבון ה-PayPal שלך בעתיד. האישור יבוטל ואתה לא תחויב.</p>");
        map2.put("LOG_IN_TO_PAYPAL|AU", "היכנס עם PayPal");
        map2.put("LOG_IN_TO_PAYPAL|GB", "היכנס עם PayPal");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם השותף.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך ולחץ על סמל גלגל השיניים. עבור אל <strong>אבטחה</strong>, בחר <strong>היכנס עם PayPal</strong> והסר שותף זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> שלך והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם השותף.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך ולחץ על סמל גלגל השיניים. עבור אל <strong>אבטחה</strong>, בחר <strong>היכנס עם PayPal</strong> והסר שותף זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם השותף.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך ולחץ על סמל גלגל השיניים. עבור אל <strong>אבטחה</strong>, בחר <strong>היכנס עם PayPal</strong> והסר שותף זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, לחץ על סמל גלגל השיניים בפינה הימנית העליונה, בחר <strong>מרכז האבטחה</strong>, בחר <strong>היכנס עם PayPal</strong> והסר את בעל העסק. אם אתה עדיין משתמש באתר הקלאסי, עבור אל <strong>הפרופיל שלי</strong>, בחר <strong>הגדרות החשבון שלי</strong>, בחר <strong>היכנס עם PayPal</strong> והסר את בעל העסק.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם השותף.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך ותחת הגדרות ה<strong>פרופיל</strong>, עבור אל <strong>היכנס עם PayPal</strong> והסר שותף זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.it, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> שלך והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> שלך והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם השותף.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.ru, לחץ על סמל גלגל השיניים בפינה הימנית העליונה, בחר בלשונית <strong>אבטחה</strong> והסר שותף זה תחת האפשרות <strong>היכנס עם PayPal\u200f</strong>.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של השותף.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס לחשבון ה-PayPal שלך, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com.tr, לחץ על סמל גלגל השיניים בפינה הימנית העליונה, בחר בלשונית <strong>אבטחה</strong> והסר שותף זה תחת האפשרות <strong>היכנס עם PayPal\u200f</strong>.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל אפשרויות <strong>היכנס עם PayPal</strong> תחת הגדרות ה<strong>פרופיל</strong> והסר בעל עסק זה.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>\u200e%s\u200e\u200f</strong></h1><p>כל פרטי העסקה הרלוונטיים ישותפו עם בעל העסק.</p><p>כדי לבטל את הסכמתך, היכנס אל paypal.com, עבור אל <strong>פרופיל</strong>, <strong>אבטחה</strong>, מצא את האפשרות <strong>היכנס עם PayPal</strong> והסר בעל עסק זה.</p><p>PayPal אינה אחראית לפעולות או שגיאות כלשהן מצדו של בעל העסק.</p>");
        Map map3 = f21381c;
        map3.put("AMOUNT_MISMATCH", "הסכום הכולל של הפריטים בעגלת הקניות אינו תואם את סכום המכירה.");
        map3.put("AUTHORIZATION_ALREADY_COMPLETED", "אישור זה כבר הושלם.");
        map3.put("AUTHORIZATION_CANNOT_BE_VOIDED", "לא ניתן לבטל את תוקף האישור.");
        map3.put("AUTHORIZATION_EXPIRED", "פג תוקף האישור.");
        map3.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "מזהה האישור המבוקש לא קיים.");
        map3.put("AUTHORIZATION_VOIDED", "האישור בוטל.");
        map3.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "ניתן לאשר מחדש רק את האישור המקורי, לא אישור מחדש.");
        map3.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "לא ניתן לבצע אישור מחדש במסגרת תקופת הכיבוד.");
        map3.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "הסכום חורג מהמגבלה המותרת.");
        map3.put("CARD_TOKEN_PAYER_MISMATCH", "לא ניתן לגשת לפרטי הכרטיס השמורים.");
        map3.put("CREDIT_CARD_CVV_CHECK_FAILED", "פרטי הכרטיס לא תקפים. תקן ושלח שוב.");
        map3.put("CREDIT_CARD_REFUSED", "הכרטיס נדחה.");
        map3.put("CURRENCY_MISMATCH", "על מטבע האיסוף להיות זהה למטבע האישור.");
        map3.put("CURRENCY_NOT_ALLOWED", "PayPal אינה תומכת במטבע זה כעת.");
        map3.put("DATA_RETRIEVAL", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        map3.put("DUPLICATE_REQUEST_ID", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        map3.put("EXPIRED_CREDIT_CARD", "פג תוקף הכרטיס");
        map3.put("EXPIRED_CREDIT_CARD_TOKEN", "הפרטים של כרטיס זה כבר אינם נמצאים ברשומות.\nשלח שוב.");
        map3.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "התכונה אינה נתמכת עבור ספק זה.");
        map3.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "כבר בוצע החזר חלקי עבור עסקה זו.");
        map3.put("IMMEDIATE_PAY_NOT_SUPPORTED", "תשלום מיידי אינו נתמך עבור המטרה (Intent) המבוקשת.");
        map3.put("INSTRUMENT_DECLINED", "שיטת התשלום שבחרת לא התקבלה. בחר שיטה אחרת.");
        map3.put("INSUFFICIENT_FUNDS", "הקונה לא יכול לשלם - מחסור בכסף.");
        map3.put("INTERNAL_SERVICE_ERROR", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        map3.put("INVALID_ACCOUNT_NUMBER", "מספר חשבון זה לא קיים.");
        map3.put("INVALID_ARGUMENT", "העסקה נדחתה עקב סיבות טכניות");
        map3.put("INVALID_CITY_STATE_ZIP", "שילוב לא חוקי של עיר/מדינה/מיקוד.");
        map3.put("INVALID_FACILITATOR_CONFIGURATION", "לא ניתן לעבד את העסקה עקב הגדרת גורם מתווך בלתי-תקפה.");
        map3.put("INVALID_PAYER_ID", "שגיאת מערכת (מזהה משלם לא חוקי). נסה שוב מאוחר יותר.");
        map3.put("INVALID_RESOURCE_ID", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        map3.put("PAYEE_ACCOUNT_INVALID", "לחשבון הספק אין כתובת אימייל מאושרת.");
        map3.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "ספק זה אינו יכול לקבל תשלומים כעת.");
        map3.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "לחשבון הספק אין כתובת אימייל מאושרת.");
        map3.put("PAYEE_ACCOUNT_RESTRICTED", "ספק זה אינו יכול לקבל תשלומים כעת.");
        map3.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "החשבון שלך נעול או סגור.");
        map3.put("PAYER_ACCOUNT_RESTRICTED", "החשבון שלך מוגבל.");
        map3.put("PAYER_CANNOT_PAY", "אינך יכול לשלם עבור עסקה זו באמצעות PayPal\u200f.");
        map3.put("PAYER_EMPTY_BILLING_ADDRESS", "נדרשת כתובת לחיוב עבור עסקאות בכרטיס אשראי שאינן משולמות באמצעות PayPal\u200f.");
        map3.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "לא ניתן לגשת לפרטי הכרטיס השמורים.");
        map3.put("PAYMENT_APPROVAL_EXPIRED", "פג התוקף של אישור התשלום.");
        map3.put("PAYMENT_EXPIRED", "פג תוקף התשלום.");
        map3.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "המשלם לא אישר את התשלום.");
        map3.put("PAYMENT_REQUEST_ID_INVALID", "מזהה העסקה של PayPal לא חוקי. נסה שוב מאוחר יותר.");
        map3.put("PAYMENT_STATE_INVALID", "בקשה זו אינה חוקית עקב מצבו הנוכחי של התשלום.");
        map3.put("PERMISSION_DENIED", "אין הרשאה לפעולה המבוקשת.");
        map3.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "ההחזר המבוקש חורג מסכום העסקה המקורית.");
        map3.put("REFUND_TIME_LIMIT_EXCEEDED", "עסקה זו ישנה מכדי שניתן יהיה לבצע החזר.");
        map3.put("REQUIRED_SCOPE_MISSING", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        map3.put("TOO_MANY_REAUTHORIZATIONS", "לא ניתן לבצע אישורים מחדש נוספים לאישור זה.");
        map3.put("TRANSACTION_ALREADY_REFUNDED", "כבר בוצע החזר עבור עסקה זו.");
        map3.put("TRANSACTION_LIMIT_EXCEEDED", "הסכום חורג מהמגבלה המותרת.");
        map3.put("TRANSACTION_REFUSED", "העסקה נדחתה.");
        map3.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "העסקה נדחתה.");
        map3.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "הגדרת פרופיל בעל העסק מוגדרת לדחייה אוטומטית של עסקאות מסויימות.");
        map3.put("UNKNOWN_ERROR", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        map3.put("UNSUPPORTED_PAYEE_COUNTRY", "הארץ אינה נתמכת.");
        map3.put("VALIDATION_ERROR", "פרטי התשלום אינם חוקיים. תקן ושלח שוב.");
        map3.put("ORDER_ALREADY_COMPLETED", "ההזמנה כבר בוטלה, הושלמה או שתוקפה פג.");
        map3.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "ההזמנה הגיעה למספר המרבי המותר של אישורים.");
        map3.put("ORDER_VOIDED", "ההזמנה בוטלה.");
        map3.put("ORDER_CANNOT_BE_VOIDED", "מצב ההזמנה מונע את ביטולה.");
        map3.put("INVALID_EXPERIENCE_PROFILE_ID", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        map3.put("UNAUTHORIZED_PAYMENT", "בעל העסק אינו מקבל תשלום מסוג זה.");
        map3.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "המטבע לא נתמך עבור סוג הכרטיס.");
        map3.put("DCC_CC_TYPE_NOT_SUPPORTED", "סוג הכרטיס לא נתמך.");
        map3.put("ADDRESS_ADDITION_ERROR", "אירעה שגיאה בעת הוספת כתובת למשלוח לחשבון ה-PayPal\u200f.");
        map3.put("DUPLICATE_TRANSACTION", "עסקה כפולה.");
        map3.put("INVALID_SHIPPING_ADDRESS", "הכתובת למשלוח שהוזנה אינה חוקית.");
        map3.put("PAYMENT_CREATION_ERROR", "אירעה בעיה בהגדרת תשלום זה. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        map3.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "אירעה בעיה בהגדרת תשלום זה - פג תוקף הכרטיס שלך. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        map3.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "אירעה בעיה בהגדרת תשלום זה - נדרש אמצעי תשלום מיידי, כגון כרטיס אשראי. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "אירעה בעיה בהגדרת תשלום זה - יש לאשר את הכרטיס. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "אירעה בעיה בהגדרת תשלום זה - אפליקציה זו מחייבת שהחשבון שלך יכיל מספר טלפון. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "אירעה בעיה בהגדרת תשלום זה - החשבון צריך להכיל מקור כספי חוקי, כגון חשבון בנק או כרטיס תשלום. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        map3.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "אירעה בעיה בהגדרת תשלום זה - היתרה שלך שלילית. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        map3.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "אירעה בעיה בהגדרת תשלום זה - הגעת למגבלת השליחה שלך. בקר באתר PayPal כדי לבדוק את החשבון שלך.");
        map3.put("AUTH_RC_RISK_FAILURE", "נדחה עקב סיכון.");
        map3.put("AUTH_RC_OFAC_BLOCKED_IP", "לקוח לא אושר.");
        map3.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "לקוח לא אושר.");
        map3.put("invalid_user", "שם משתמש/סיסמה שגויים. נסה שוב.");
        map3.put("locked_user", "חשבון ה-PayPal שלך ננעל באופן זמני. נסה שוב מאוחר יותר, או עבור אל www.paypal.co.il כדי לבטל את נעילת חשבון ה-PayPal שלך באופן מיידי.");
        map3.put("max_attempts_exceeded", "חרגת ממספר ניסיונות הכניסה המרבי. נסה שוב מאוחר יותר.");
        map3.put("invalid_request", "אירעה שגיאה.");
        map3.put("unauthorized_client", "הבקשה לא אושרה.");
        map3.put("access_denied", "הבקשה לא אושרה.");
        map3.put("unsupported_response_type", "אירעה שגיאה.");
        map3.put("invalid_scope", "הבקשה לא אושרה.");
        map3.put("server_error", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        map3.put("temporarily_unavailable", "שגיאת מערכת. נסה שוב מאוחר יותר.");
        map3.put("stepup_required", "לא ניתן להשלים את כניסתך לחשבון בשלב זה. נסה שוב מאוחר יותר, או עבור אל www.paypal.co.il כדי לפתור בעיות אבטחה אפשריות עם חשבון ה-PayPal שלך.");
        map3.put("account_locked_generate_challenge_limit_exceeded", "נסיונות כניסה רבים מדי. נסה שוב מאוחר יותר, או צור קשר עם PayPal לקבלת עזרה.");
    }

    @Override // com.paypal.android.sdk.y4
    public final String a() {
        return "he";
    }

    @Override // com.paypal.android.sdk.y4
    public final /* synthetic */ String a(Enum r32, String str) {
        ft ftVar = (ft) r32;
        String str2 = ftVar.toString() + "|" + str;
        Map map = f21380b;
        return (String) (map.containsKey(str2) ? map.get(str2) : f21379a.get(ftVar));
    }

    @Override // com.paypal.android.sdk.y4
    public final String a(String str) {
        return (String) f21381c.get(str);
    }
}
