package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;
/* loaded from: classes2.dex */
public final class j5 implements y4 {

    /* renamed from: a  reason: collision with root package name */
    private static final Map f21401a = new HashMap();

    /* renamed from: b  reason: collision with root package name */
    private static final Map f21402b = new HashMap();

    /* renamed from: c  reason: collision with root package name */
    private static final Map f21403c = new HashMap();

    public j5() {
        Map map = f21401a;
        map.put(ft.AGREE_AND_PAY, "Accetta e paga");
        map.put(ft.AND_OTHER_FUNDING_SOURCES, "e altri");
        map.put(ft.AUTHENTICATING, "Autenticazione…");
        map.put(ft.BACK_BUTTON, "Indietro");
        map.put(ft.BACKUP_FUNDING_SOURCE, "Di riserva");
        map.put(ft.CANCEL, "Annulla");
        map.put(ft.CARDTYPE_AMERICANEXPRESS, "American Express");
        map.put(ft.CARDTYPE_CARTAAURA, "Carta Aura");
        map.put(ft.CARDTYPE_CARTEAURORE, "Carta Aura");
        map.put(ft.CARDTYPE_CARTAPREPAGATAPAYPAL, "Prepagata PayPal");
        map.put(ft.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        map.put(ft.CARDTYPE_COFINOGA, "Cofinoga");
        map.put(ft.CARDTYPE_DELTA, "Delta");
        map.put(ft.CARDTYPE_DISCOVER, "Discover");
        map.put(ft.CARDTYPE_ELECTRON, "Electron");
        map.put(ft.CARDTYPE_JCB, "JCB");
        map.put(ft.CARDTYPE_MAESTRO, "Maestro");
        map.put(ft.CARDTYPE_MASTERCARD, "MasterCard");
        map.put(ft.CARDTYPE_POSTEPAY, "Postepay");
        map.put(ft.CARDTYPE_4ETOILES, "4 étoiles");
        map.put(ft.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        map.put(ft.CARDTYPE_VISA, "Visa");
        map.put(ft.CHANGE_PAYMENT_METHOD, "Modifica metodo di pagamento");
        map.put(ft.CHECKING_ACCOUNT_FOR_INSTITUTION, "Conto corrente");
        map.put(ft.CHECKING_DEVICE, "Controllo dispositivo…");
        map.put(ft.CLEAR_CREDIT_CARD_INFO, "Rimuovi dati della carta");
        map.put(ft.CONFIRM, "Conferma");
        map.put(ft.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Rimuovere i dati della carta?");
        map.put(ft.CONFIRM_CHARGE_CREDIT_CARD, "Addebita importo sulla carta");
        map.put(ft.CONFIRM_LOG_OUT, "Vuoi uscire da PayPal?");
        map.put(ft.CONFIRM_SEND_PAYMENT, "Paga");
        map.put(ft.CONSENT_AGREEMENT_AGREE, "Accetta");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Data creazione conto");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Stato del conto");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Tipo di conto");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Indirizzo");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Fascia di età");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Data di nascita");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Indirizzo email");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Nome e cognome");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Sesso");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Lingua");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Locale");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefono");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Fuso orario");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTES, "Condividi il seguente: %s.");
        map.put(ft.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Usa Pagamento express.");
        map.put(ft.CONSENT_AGREEMENT_INTRO, "%s ti chiede di:");
        map.put(ft.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Condividi i <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map.put(ft.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Per effettuare una scelta, attiva la visualizzazione dei metodi di pagamento.");
        map.put(ft.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.");
        map.put(ft.CONSENT_AGREEMENT_LOYALTY_CARD, "consentirgli di aggiungere e gestire la propria carta fedeltà nel tuo portafoglio PayPal.");
        map.put(ft.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Accettare l’<a href='%2$s'></a> Informativa sulla privacy<a href='%3$s'> e le</a> Condizioni d’uso di %1$s.");
        map.put(ft.CONSENT_AGREEMENT_REQUEST_MONEY, "Consentirgli di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        map.put(ft.CONSENT_AGREEMENT_SEND_MONEY, "Consentirgli di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        map.put(ft.CONSENT_AGREEMENT_TITLE, "Consenso");
        map.put(ft.EMAIL, "Email");
        map.put(ft.ENVIRONMENT_MOCK_DATA, "Dati di esempio");
        map.put(ft.ENVIRONMENT_SANDBOX, "Sandbox");
        map.put(ft.EXPIRES_ON_DATE, "Scadenza");
        map.put(ft.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal condivide solo i tuoi metodi di pagamento disponibili per l’utilizzo.</p>");
        map.put(ft.FORGOT_PASSWORD, "Password dimenticata?");
        map.put(ft.FROM_ACCOUNT, "Da");
        map.put(ft.FUTURE_PAYMENT_METHOD_QUESTION, "Come vuoi pagare i prossimi acquisti su %1$s?");
        map.put(ft.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Gli importi dei prossimi pagamenti effettuati con PayPal da questa app verranno prelevati dal tuo metodo di pagamento predefinito.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>Si applica la sezione Pagamenti automatici delle <a href='%s'>Condizioni d’uso PayPal</a>.</p><p>Per verificare il funzionamento dell’addebito dei pagamenti futuri sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p>");
        map.put(ft.INTERNAL_ERROR, "Errore interno");
        map.put(ft.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Cliccando il pulsante di seguito, accetto le <a href='%1$s'>Condizioni d’uso PayPal</a> e dichiaro di rispettare le leggi e normative del Giappone, tra cui le sanzioni previste per i pagamenti alla Corea del Nord e all’Iran in base al <a href='%2$s'>Foreign Exchange and Foreign Trade Act</a> (Legge sugli scambi e sul commercio estero), per completare la transazione.</p>");
        map.put(ft.LOG_IN, "Accedi");
        map.put(ft.LOG_IN_TO_PAYPAL, "Log in con PayPal");
        map.put(ft.LOG_OUT_BUTTON, "Esci");
        map.put(ft.LOG_OUT, "Esci");
        map.put(ft.OK, "OK");
        map.put(ft.PASSWORD, "Password");
        map.put(ft.PAY_AFTER_DELIVERY, "Paga dopo la consegna");
        map.put(ft.PAY_WITH, "Paga con");
        map.put(ft.PAY_WITH_CARD, "Paga con una carta");
        map.put(ft.PAYPAL_BALANCE, "Saldo PayPal");
        map.put(ft.PAYPAL_CREDIT, "PayPal Credit");
        map.put(ft.PHONE, "Telefono");
        map.put(ft.PIN, "PIN");
        map.put(ft.PREFERRED_PAYMENT_METHOD, "Metodo di pagamento preferito");
        map.put(ft.PRIVACY, "PayPal protegge la tua <a href='%s'>privacy</a> e i tuoi dati.");
        map.put(ft.PROCESSING, "Elaborazione in corso");
        map.put(ft.REMEMBER_CARD, "Ricorda dati carta");
        map.put(ft.REQUEST_MONEY, "Richiedi denaro");
        map.put(ft.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
        map.put(ft.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Conto corrente");
        map.put(ft.SEND_MONEY, "Invia denaro");
        map.put(ft.SERVER_PROBLEM, "Si è verificato un problema con i nostri server. Riprova.");
        map.put(ft.SESSION_EXPIRED_MESSAGE, "Ripeti l’accesso a PayPal.");
        map.put(ft.SESSION_EXPIRED_TITLE, "Sessione scaduta");
        map.put(ft.SHIPPING_ADDRESS, "Indirizzo di spedizione");
        map.put(ft.SIGN_UP, "Non hai un conto PayPal? Registrati");
        map.put(ft.STAY_LOGGED_IN, "Rimani connesso");
        map.put(ft.SYSTEM_ERROR_WITH_CODE, "Errore di sistema (%s). Riprova più tardi.");
        map.put(ft.TRY_AGAIN, "Riprova");
        map.put(ft.TWO_FA_REQUIRED_ERROR, "Impossibile effettuare l’accesso perché sul tuo conto è attiva la doppia autenticazione.");
        map.put(ft.TWO_FACTOR_AUTH_TITLE, "Codice di sicurezza");
        map.put(ft.TWO_FACTOR_AUTH_SUBTITLE, "Ricevi un SMS sul tuo telefono. Il codice a 6 cifre sarà valido per 5 minuti.");
        map.put(ft.TWO_FACTOR_AUTH_SENDING_DIALOG, "Invio SMS in corso");
        map.put(ft.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Immetti il codice di sicurezza a 6 cifre");
        map.put(ft.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Numero di cellulare");
        map.put(ft.TWO_FACTOR_AUTH_SEND_SMS, "Ricevi SMS");
        map.put(ft.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Ricevi un altro SMS");
        map.put(ft.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Impossibile effettuare l’accesso perché sul tuo conto è attiva la doppia autenticazione. Visita il sito PayPal per attivare la chiave di accesso.");
        map.put(ft.UNAUTHORIZED_DEVICE_MESSAGE, "Pagamenti da questo dispositivo non consentiti.");
        map.put(ft.UNAUTHORIZED_DEVICE_TITLE, "Dispositivo non autorizzato");
        map.put(ft.UNAUTHORIZED_MERCHANT_MESSAGE, "I pagamenti a questo venditore non sono consentiti (clientId non valido).");
        map.put(ft.UNAUTHORIZED_MERCHANT_TITLE, "Sito non valido");
        map.put(ft.UNEXPECTED_PAYMENT_FLOW, "Si è verificato un problema durante l’elaborazione del pagamento. Riprova.");
        map.put(ft.UNKNOWN_FUNDING_SOURCE, "Metodo non riconosciuto");
        map.put(ft.WE_ARE_SORRY, "Spiacenti");
        map.put(ft.YOUR_ORDER, "Il tuo ordine");
        map.put(ft.ANDROID_OS_TOO_OLD, "Questo dispositivo non dialoga con PayPal perché la versione di Android è obsoleta. Aggiorna Android o prova con un dispositivo più recente.");
        map.put(ft.CLEAR_CC_ALERT_TITLE, "Rimuovere la carta?");
        map.put(ft.CONSENT_FAILED_ALERT_TITLE, "Consenso non riuscito");
        map.put(ft.CONNECTION_FAILED_TITLE, "Connessione non riuscita");
        map.put(ft.LOGIN_FAILED_ALERT_TITLE, "Accesso non riuscito");
        map.put(ft.LOGIN_WITH_EMAIL, "Accedi con la password");
        map.put(ft.LOGIN_WITH_PHONE, "Accedi con il PIN");
        map.put(ft.ONE_MOMENT, "Attendi…");
        map.put(ft.PAY_FAILED_ALERT_TITLE, "Pagamento non riuscito");
        map.put(ft.SCAN_CARD_ICON_DESCRIPTION, "Scansione");
        map.put(ft.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Codice di sicurezza errato. Riprova.");
        map.put(ft.VIA_LABEL, "tramite");
        map.put(ft.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Errore di sistema. Riprova più tardi.");
        Map map2 = f21402b;
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Condividi con loro i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Condividi i dati dei <a href='%1$s'>metodi di pagamento</a> collegati al tuo conto PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Condividi i <a href='%1$s'>metodi di pagamento</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.</p><p>Vedi <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>Pagamenti automatici e Contratto di addebito automatico PayPal</a> per maggiori informazioni.</p>");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti effettuati su %2$s e pagati con PayPal. Autorizzi PayPal a pagare tutti gli importi richiesti da %3$s.</p><p>Vedi <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>Pagamenti automatici e Contratto di addebito automatico PayPal</a> per maggiori informazioni.</p>");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti pagati con PayPal. Autorizzi e dai istruzioni a PayPal per il pagamento di tutti gli importi.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti pagati con PayPal. Autorizzi e dai istruzioni a PayPal per il pagamento di tutti gli importi.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Autorizza l’addebito</a> dei prossimi acquisti pagati con PayPal. Autorizzi e dai istruzioni a PayPal per il pagamento di tutti gli importi.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Preautorizza i prossimi pagamenti dal tuo conto PayPal senza effettuare ogni volta l’accesso al conto. <a href='%1$s'>Vedi le condizioni aggiuntive</a>, tra cui i metodi di pagamento e le modalità di annullamento dei pagamenti preautorizzati.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Consentire a %2$s di <a href='%1$s'>richiedere denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Consentire a %2$s di <a href='%1$s'>inviare denaro</a> a tuo nome fino alla revoca del consenso.");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Metodi di pagamento</strong></h1><p>PayPal rivela solo quali dei tuoi metodi di pagamento sono disponibili.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito (il saldo PayPal, il conto bancario, la carta di credito o di debito, in quest’ordine) verrà usato per pagare gli acquisti con PayPal. Se sul tuo metodo di pagamento preferito non è presente denaro sufficiente per l’acquisto, la banca o la società emittente della carta potrebbe addebitarti una tariffa.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Modifica</strong> accanto a “Log in con PayPal”.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Per pagare gli acquisti con PayPal verrà usato il tuo saldo PayPal o la tua carta di credito o di debito (bancomat) principale.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Gli importi dei prossimi pagamenti effettuati con PayPal da questa app verranno prelevati dal tuo metodo di pagamento predefinito.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Si applica la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a>.</p><p>Per verificare il funzionamento dell’addebito dei pagamenti futuri sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Per maggiori informazioni, vedi la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Vedi la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a> per maggiori informazioni.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Per pagare gli acquisti con PayPal verrà usato il tuo saldo PayPal o la tua carta di credito o di debito (bancomat) principale.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Per maggiori informazioni, vedi la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Per maggiori informazioni, vedi la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal, questa app potrebbe simulare una transazione di prova, senza un reale trasferimento di denaro.</p><p>Il tuo metodo di pagamento predefinito verrà usato per pagare gli acquisti con PayPal.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong>, quindi rimuovi questo commerciante dall’elenco.</p><p>Per maggiori informazioni, vedi la sezione “Pagamenti automatici” delle <a href='%s'>Condizioni d’uso PayPal</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Consenso ai pagamenti preautorizzati</strong></h1><p>Come prima opzione per pagare i tuoi acquisti, verrà usato il tuo saldo PayPal. Se non è sufficiente, verranno usati, nell’ordine, il conto bancario, PayPal Credit, la carta di debito (bancomat), la carta di credito e/o gli eCheck.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante dall’elenco.</p><p>Potrebbe essere richiesta l’autorizzazione di un piccolo pagamento per verificare la possibilità di addebitare i pagamenti preautorizzati sul tuo conto PayPal. L’autorizzazione verrà annullata e non ti verrà addebitato alcun importo.</p>");
        map2.put("LOG_IN_TO_PAYPAL|AU", "Log in con PayPal");
        map2.put("LOG_IN_TO_PAYPAL|GB", "Log in con PayPal");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal e clicca l’icona Profilo. Clicca <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal e clicca l’icona Profilo. Clicca <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal e clicca l’icona Profilo. Clicca <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona Profilo &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco. Se usi ancora la versione classica del sito, vai al tuo <strong>Profilo</strong> &gt; <strong>Impostazioni</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il Partner.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del Partner.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, clicca l’icona Profilo &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il Partner dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PayPal, seleziona l’icona <strong>Profilo</strong> &gt; Sicurezza &gt; <strong>Log in con PayPal</strong> e rimuovi questo commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Tutti i dettagli rilevanti della transazione verranno condivisi con il commerciante.</p><p>Per annullare il consenso, accedi al tuo conto PyaPal, clicca l’icona <strong>Profilo</strong> &gt; <strong>Sicurezza</strong> &gt; <strong>Log in con PayPal</strong> e rimuovi il commerciante dall’elenco.</p><p>PayPal non è responsabile di azioni o errori da parte del commerciante.</p>");
        Map map3 = f21403c;
        map3.put("AMOUNT_MISMATCH", "Il totale del carrello non corrisponde all’importo delle vendite.");
        map3.put("AUTHORIZATION_ALREADY_COMPLETED", "L’autorizzazione è già stata completata.");
        map3.put("AUTHORIZATION_CANNOT_BE_VOIDED", "L’autorizzazione è in una provincia in cui non può essere annullata.");
        map3.put("AUTHORIZATION_EXPIRED", "L’autorizzazione è scaduta.");
        map3.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "L’ID autorizzazione richiesto non esiste.");
        map3.put("AUTHORIZATION_VOIDED", "L’autorizzazione è stata annullata.");
        map3.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "È possibile riautorizzare solo le autorizzazioni originali.");
        map3.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "La riautorizzazione non è consentita nel periodo di validità.");
        map3.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "L’importo supera il limite consentito.");
        map3.put("CARD_TOKEN_PAYER_MISMATCH", "Impossibile accedere ai dati della carta in archivio.");
        map3.put("CREDIT_CARD_CVV_CHECK_FAILED", "I dati della carta non sono validi. Correggi i tuoi dati e riprova.");
        map3.put("CREDIT_CARD_REFUSED", "Carta rifiutata.");
        map3.put("CURRENCY_MISMATCH", "La valuta di riscossione deve essere uguale a quella di autorizzazione.");
        map3.put("CURRENCY_NOT_ALLOWED", "Valuta non supportata da PayPal.");
        map3.put("DATA_RETRIEVAL", "Errore di sistema. Riprova più tardi.");
        map3.put("DUPLICATE_REQUEST_ID", "Errore di sistema. Riprova più tardi.");
        map3.put("EXPIRED_CREDIT_CARD", "La carta è scaduta");
        map3.put("EXPIRED_CREDIT_CARD_TOKEN", "I dati di questa carta non sono più in archivio.\nInoltrali di nuovo.");
        map3.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "La funzione non è supportata per questo beneficiario.");
        map3.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "La transazione è stata già rimborsata parzialmente.");
        map3.put("IMMEDIATE_PAY_NOT_SUPPORTED", "L’opzione di pagamento immediato non è supportata per la finalità impostata.");
        map3.put("INSTRUMENT_DECLINED", "Il metodo di pagamento selezionato non è stato accettato. Scegli un altro metodo di pagamento.");
        map3.put("INSUFFICIENT_FUNDS", "L’acquirente non può pagare per denaro insufficiente.");
        map3.put("INTERNAL_SERVICE_ERROR", "Errore di sistema. Riprova più tardi.");
        map3.put("INVALID_ACCOUNT_NUMBER", "Il numero di conto non esiste.");
        map3.put("INVALID_ARGUMENT", "Transazione rifiutata per problemi tecnici");
        map3.put("INVALID_CITY_STATE_ZIP", "Combinazione Città/Provincia/CAP non valida.");
        map3.put("INVALID_FACILITATOR_CONFIGURATION", "Impossibile elaborare la transazione per configurazione non valida.");
        map3.put("INVALID_PAYER_ID", "Errore di sistema (ID acquirente non valido). Riprova più tardi.");
        map3.put("INVALID_RESOURCE_ID", "Errore di sistema. Riprova più tardi.");
        map3.put("PAYEE_ACCOUNT_INVALID", "Il conto del beneficiario non ha un’email confermata.");
        map3.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Questo venditore non può ricevere pagamenti al momento.");
        map3.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Il conto del beneficiario non ha un’email confermata.");
        map3.put("PAYEE_ACCOUNT_RESTRICTED", "Questo venditore non può ricevere pagamenti al momento.");
        map3.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Il tuo conto è bloccato o chiuso.");
        map3.put("PAYER_ACCOUNT_RESTRICTED", "Il tuo conto è stato limitato.");
        map3.put("PAYER_CANNOT_PAY", "Impossibile inviare questo pagamento con PayPal.");
        map3.put("PAYER_EMPTY_BILLING_ADDRESS", "L’indirizzo di fatturazione è obbligatorio per le transazioni con carta non effettuate con PayPal.");
        map3.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Impossibile accedere ai dati della carta in archivio.");
        map3.put("PAYMENT_APPROVAL_EXPIRED", "L’approvazione del pagamento è scaduta.");
        map3.put("PAYMENT_EXPIRED", "Il pagamento è scaduto.");
        map3.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "L’acquirente non ha approvato il pagamento.");
        map3.put("PAYMENT_REQUEST_ID_INVALID", "Il codice (ID) di richiesta PayPal non è valido. Riprova più tardi.");
        map3.put("PAYMENT_STATE_INVALID", "Richiesta non valida nella provincia di pagamento.");
        map3.put("PERMISSION_DENIED", "L’operazione richiesta non è autorizzata.");
        map3.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Il rimborso richiesto supera l’importo della transazione originale.");
        map3.put("REFUND_TIME_LIMIT_EXCEEDED", "Questa transazione è troppo datata per essere rimborsata.");
        map3.put("REQUIRED_SCOPE_MISSING", "Errore di sistema. Riprova più tardi.");
        map3.put("TOO_MANY_REAUTHORIZATIONS", "Per questa autorizzazione non sono più consentite riautorizzazioni.");
        map3.put("TRANSACTION_ALREADY_REFUNDED", "La transazione è stata già rimborsata.");
        map3.put("TRANSACTION_LIMIT_EXCEEDED", "L’importo supera il limite consentito.");
        map3.put("TRANSACTION_REFUSED", "La transazione è stata rifiutata.");
        map3.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "La transazione è stata rifiutata.");
        map3.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Le preferenze del commerciante sono impostate per rifiutare automaticamente determinate transazioni.");
        map3.put("UNKNOWN_ERROR", "Errore di sistema. Riprova più tardi.");
        map3.put("UNSUPPORTED_PAYEE_COUNTRY", "Il tuo Paese non è supportato.");
        map3.put("VALIDATION_ERROR", "I dati di pagamento non sono validi. Correggi i tuoi dati e riprova.");
        map3.put("ORDER_ALREADY_COMPLETED", "L’ordine è stato già annullato, è scaduto o completato.");
        map3.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Il numero massimo di autorizzazioni consentite per l’ordine è stato raggiunto.");
        map3.put("ORDER_VOIDED", "L’ordine è stato annullato.");
        map3.put("ORDER_CANNOT_BE_VOIDED", "L’ordine è in uno stato che impedisce l’annullamento.");
        map3.put("INVALID_EXPERIENCE_PROFILE_ID", "Errore di sistema. Riprova più tardi.");
        map3.put("UNAUTHORIZED_PAYMENT", "Il commerciante non accetta questo tipo di pagamenti.");
        map3.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valuta non supportata per il tipo di carta.");
        map3.put("DCC_CC_TYPE_NOT_SUPPORTED", "Tipo di carta non supportato.");
        map3.put("ADDRESS_ADDITION_ERROR", "Si è verificato un errore durante l’aggiunta dell’indirizzo di spedizione al conto PayPal.");
        map3.put("DUPLICATE_TRANSACTION", "Transazione doppia");
        map3.put("INVALID_SHIPPING_ADDRESS", "L’indirizzo di spedizione non è valido.");
        map3.put("PAYMENT_CREATION_ERROR", "Si è verificato un problema nella disposizione del pagamento. Vai su paypal.it e controlla il tuo conto.");
        map3.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Si è verificato un problema nella disposizione del pagamento: la tua carta è scaduta. Vai su paypal.it e controlla il tuo conto.");
        map3.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Si è verificato un problema nella disposizione del pagamento: è richiesto un pagamento immediato, ad esempio una carta di credito. Vai su paypal.it e controlla il tuo conto.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Si è verificato un problema nella disposizione del pagamento: la carta deve essere confermata. Vai su paypal.it e controlla il tuo conto.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Si è verificato un problema nella disposizione del pagamento: questa applicazione richiede che sul tuo conto sia registrato un numero di telefono. Vai su paypal.it e controlla il tuo conto.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Si è verificato un problema nella disposizione del pagamento: il conto necessita di un metodo di pagamento valido, ad esempio un conto bancario o una carta di pagamento. Vai su paypal.it e controlla il tuo conto.");
        map3.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Si è verificato un problema nella disposizione del pagamento: il tuo saldo è negativo. Vai su paypal.it e controlla il tuo conto.");
        map3.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Si è verificato un problema nella disposizione del pagamento: hai raggiunto il tuo limite di invio. Vai su paypal.it e controlla il tuo conto.");
        map3.put("AUTH_RC_RISK_FAILURE", "Rifiutata per motivi di rischio.");
        map3.put("AUTH_RC_OFAC_BLOCKED_IP", "Client non autorizzato.");
        map3.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Client non autorizzato.");
        map3.put("invalid_user", "Email o password non corretta. Riprova.");
        map3.put("locked_user", "Il tuo conto PayPal è stato temporaneamente bloccato. Riprova più tardi o accedi a www.paypal.com per sbloccare immediatamente il tuo conto PayPal.");
        map3.put("max_attempts_exceeded", "Troppi tentativi di accesso non riusciti. Riprova più tardi.");
        map3.put("invalid_request", "Si è verificato un errore.");
        map3.put("unauthorized_client", "Richiesta non autorizzata.");
        map3.put("access_denied", "Richiesta non autorizzata.");
        map3.put("unsupported_response_type", "Si è verificato un errore.");
        map3.put("invalid_scope", "Richiesta non autorizzata.");
        map3.put("server_error", "Errore di sistema. Riprova più tardi.");
        map3.put("temporarily_unavailable", "Errore di sistema. Riprova più tardi.");
        map3.put("stepup_required", "Non è possibile completare l’accesso. Riprova più tardi o accedi a www.paypal.it per risolvere eventuali problema di sicurezza del tuo conto PayPal.");
        map3.put("account_locked_generate_challenge_limit_exceeded", "Troppi tentativi di accesso. Riprova più tardi o contatta PayPal per richiedere assistenza.");
    }

    @Override // com.paypal.android.sdk.y4
    public final String a() {
        return "it";
    }

    @Override // com.paypal.android.sdk.y4
    public final /* synthetic */ String a(Enum r32, String str) {
        ft ftVar = (ft) r32;
        String str2 = ftVar.toString() + "|" + str;
        Map map = f21402b;
        return (String) (map.containsKey(str2) ? map.get(str2) : f21401a.get(ftVar));
    }

    @Override // com.paypal.android.sdk.y4
    public final String a(String str) {
        return (String) f21403c.get(str);
    }
}
