package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;
/* loaded from: classes2.dex */
public final class o5 implements y4 {

    /* renamed from: a  reason: collision with root package name */
    private static final Map f21488a = new HashMap();

    /* renamed from: b  reason: collision with root package name */
    private static final Map f21489b = new HashMap();

    /* renamed from: c  reason: collision with root package name */
    private static final Map f21490c = new HashMap();

    public o5() {
        Map map = f21488a;
        map.put(ft.AGREE_AND_PAY, "Godta og betal");
        map.put(ft.AND_OTHER_FUNDING_SOURCES, "og andre");
        map.put(ft.AUTHENTICATING, "Godkjenner");
        map.put(ft.BACK_BUTTON, "Tilbake");
        map.put(ft.BACKUP_FUNDING_SOURCE, "Reserve");
        map.put(ft.CANCEL, "Avbryt");
        map.put(ft.CARDTYPE_AMERICANEXPRESS, "American Express");
        map.put(ft.CARDTYPE_CARTAAURA, "Carta Aura");
        map.put(ft.CARDTYPE_CARTEAURORE, "Carte Aurore");
        map.put(ft.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        map.put(ft.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        map.put(ft.CARDTYPE_COFINOGA, "Cofinoga");
        map.put(ft.CARDTYPE_DELTA, "Delta");
        map.put(ft.CARDTYPE_DISCOVER, "Discover");
        map.put(ft.CARDTYPE_ELECTRON, "Electron");
        map.put(ft.CARDTYPE_JCB, "JCB");
        map.put(ft.CARDTYPE_MAESTRO, "Maestro");
        map.put(ft.CARDTYPE_MASTERCARD, "MasterCard");
        map.put(ft.CARDTYPE_POSTEPAY, "Postepay");
        map.put(ft.CARDTYPE_4ETOILES, "4 étoiles");
        map.put(ft.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        map.put(ft.CARDTYPE_VISA, "Visa");
        map.put(ft.CHANGE_PAYMENT_METHOD, "Endre betalingsmetode");
        map.put(ft.CHECKING_ACCOUNT_FOR_INSTITUTION, "Brukskonto");
        map.put(ft.CHECKING_DEVICE, "Kontrollerer denne enheten …");
        map.put(ft.CLEAR_CREDIT_CARD_INFO, "Fjern kortopplysningene");
        map.put(ft.CONFIRM, "Bekreft");
        map.put(ft.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Er du sikker på at du vil fjerne kortopplysningene dine?");
        map.put(ft.CONFIRM_CHARGE_CREDIT_CARD, "Belast kortet");
        map.put(ft.CONFIRM_LOG_OUT, "Er du sikker på at du vil logge av PayPal?");
        map.put(ft.CONFIRM_SEND_PAYMENT, "Betal");
        map.put(ft.CONSENT_AGREEMENT_AGREE, "Godta");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Opprettelsesdato for kontoen");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Kontostatus");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Kontotype");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adresse");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Aldersgruppe");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Fødselsdato");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "E-postadresse");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Fullt navn");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Kjønn");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Språk");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Norsk, Norge");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Tidssone");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTES, "Del følgende: %s.");
        map.put(ft.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Bruk sømløs betaling.");
        map.put(ft.CONSENT_AGREEMENT_INTRO, "%s ber om at du:");
        map.put(ft.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Del <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        map.put(ft.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Aktiver visning av finansieringskilder slik at du kan velge en.");
        map.put(ft.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp hos %2$s via PayPal. Du ber PayPal om å betale alle summer som %3$s ber om.");
        map.put(ft.CONSENT_AGREEMENT_LOYALTY_CARD, "Tillater at de legger til og administrerer et fordelskort i PayPal-lommeboken din.");
        map.put(ft.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "Godtar %1$s sine <a href='%2$s'>retningslinjer for personvern</a> og <a href='%3$s'>brukeravtale</a>.");
        map.put(ft.CONSENT_AGREEMENT_REQUEST_MONEY, "Gi vedkommende tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map.put(ft.CONSENT_AGREEMENT_SEND_MONEY, "Gi vedkommende tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map.put(ft.CONSENT_AGREEMENT_TITLE, "Godta");
        map.put(ft.EMAIL, "E-postadresse");
        map.put(ft.ENVIRONMENT_MOCK_DATA, "Eksempeldata");
        map.put(ft.ENVIRONMENT_SANDBOX, "Sandbox");
        map.put(ft.EXPIRES_ON_DATE, "Utløper");
        map.put(ft.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av betalingsmetodene dine som er tilgjengelige for bruk.</p>");
        map.put(ft.FORGOT_PASSWORD, "Har du glemt passordet?");
        map.put(ft.FROM_ACCOUNT, "Fra");
        map.put(ft.FUTURE_PAYMENT_METHOD_QUESTION, "Hvordan vil du finansiere fremtidige betalinger til %1$s er?");
        map.put(ft.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Den standard finansieringskilden din brukes til å utføre fremtidige PayPal-betalinger for denne forhandleren.</p><p>Hvis du vil avbryte denne avtalen, logger du på PayPal-kontoen, går til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Regelmessig betaling-delen av <a href='%s'>PayPals brukeravtale</a> er gjeldende.</p><p>For å kontrollere at betalinger fungerer med PayPal-kontoen din, kan denne appen simulere en liten prøvetransaksjonen, men ingen penger overføres.</p>");
        map.put(ft.INTERNAL_ERROR, "Intern feil");
        map.put(ft.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Ved å klikke på knappen nedenfor, godtar jeg vilkårene i <a href='%1$s'>PayPals brukeravtale</a> og jeg erklærer samtidig at jeg overholder japanske lover og forskrifter, herunder sanksjonsbestemmelser om betalinger til Nord-Korea og Iran, i tråd med japansk <a href='%2$s'>lovgivning om handel med utenlandske produkter og valuta</a>, for å fullføre transaksjonen.</p>");
        map.put(ft.LOG_IN, "Logg på");
        map.put(ft.LOG_IN_TO_PAYPAL, "Logg på med PayPal");
        map.put(ft.LOG_OUT_BUTTON, "Logg ut");
        map.put(ft.LOG_OUT, "Logg ut");
        map.put(ft.OK, "OK");
        map.put(ft.PASSWORD, "Passord");
        map.put(ft.PAY_AFTER_DELIVERY, "Betal etter levering");
        map.put(ft.PAY_WITH, "Betal med");
        map.put(ft.PAY_WITH_CARD, "Betal med kort");
        map.put(ft.PAYPAL_BALANCE, "PayPal-saldo");
        map.put(ft.PAYPAL_CREDIT, "PayPal Credit");
        map.put(ft.PHONE, "Telefonnummer");
        map.put(ft.PIN, "PIN-kode");
        map.put(ft.PREFERRED_PAYMENT_METHOD, "Foretrukket betalingsmetode");
        map.put(ft.PRIVACY, "PayPal beskytter <a href='%s'>personvern</a>-opplysningene dine og den økonomiske informasjonen din.");
        map.put(ft.PROCESSING, "Behandler");
        map.put(ft.REMEMBER_CARD, "Husk kortet");
        map.put(ft.REQUEST_MONEY, "Pengeforespørsel");
        map.put(ft.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        map.put(ft.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Sparekonto");
        map.put(ft.SEND_MONEY, "Betal/overfør");
        map.put(ft.SERVER_PROBLEM, "Det var et kommunikasjonsproblem med PayPal-serverne. Prøv på nytt.");
        map.put(ft.SESSION_EXPIRED_MESSAGE, "Logg deg på PayPal på nytt.");
        map.put(ft.SESSION_EXPIRED_TITLE, "Økten er utløpt");
        map.put(ft.SHIPPING_ADDRESS, "Leveringsadresse");
        map.put(ft.SIGN_UP, "Ny på PayPal? Opprett konto");
        map.put(ft.STAY_LOGGED_IN, "Forbli pålogget");
        map.put(ft.SYSTEM_ERROR_WITH_CODE, "Systemfeil (%s). Prøv på nytt senere.");
        map.put(ft.TRY_AGAIN, "Prøv på nytt");
        map.put(ft.TWO_FA_REQUIRED_ERROR, "Kan ikke logge på, fordi påloggingen til kontoen din har godkjenning med to faktorer.");
        map.put(ft.TWO_FACTOR_AUTH_TITLE, "Sikkerhetskode");
        map.put(ft.TWO_FACTOR_AUTH_SUBTITLE, "Send en tekstmelding til telefonen din. Den 6-sifrede koden du mottar, er gyldig i 5 minutter.");
        map.put(ft.TWO_FACTOR_AUTH_SENDING_DIALOG, "Sender meldingen");
        map.put(ft.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Oppgi den 6-sifrede sikkerhetskoden");
        map.put(ft.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Ditt mobilnummer");
        map.put(ft.TWO_FACTOR_AUTH_SEND_SMS, "Send melding");
        map.put(ft.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Send meldingen på nytt");
        map.put(ft.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Kan ikke logge på, fordi påloggingen til kontoen din har godkjenning med to faktorer. Gå til PayPals nettsted for å aktivere sikkerhetsnøkkelen din.");
        map.put(ft.UNAUTHORIZED_DEVICE_MESSAGE, "Betaling fra denne enheten er ikke tillatt.");
        map.put(ft.UNAUTHORIZED_DEVICE_TITLE, "Uautorisert enhet");
        map.put(ft.UNAUTHORIZED_MERCHANT_MESSAGE, "Betalinger til denne forhandleren er ikke tillatt (ugyldig bruker-id).");
        map.put(ft.UNAUTHORIZED_MERCHANT_TITLE, "Ugyldig forhandler");
        map.put(ft.UNEXPECTED_PAYMENT_FLOW, "Det oppsto et problem ved behandlingen av betalingen. Prøv på nytt.");
        map.put(ft.UNKNOWN_FUNDING_SOURCE, "Ukjent betalingsmetode");
        map.put(ft.WE_ARE_SORRY, "Vi beklager");
        map.put(ft.YOUR_ORDER, "Din bestilling");
        map.put(ft.ANDROID_OS_TOO_OLD, "Denne enheten kan ikke kommunisere med PayPal fordi androidversjonen er for gammel. Oppgrader til en nyere androidversjon, eller forsøk med en nyere enhet.");
        map.put(ft.CLEAR_CC_ALERT_TITLE, "Vil du fjerne kortet?");
        map.put(ft.CONSENT_FAILED_ALERT_TITLE, "Godkjenningen mislyktes");
        map.put(ft.CONNECTION_FAILED_TITLE, "Tilkobling mislykket");
        map.put(ft.LOGIN_FAILED_ALERT_TITLE, "Pålogging mislyktes");
        map.put(ft.LOGIN_WITH_EMAIL, "Logg på med passord");
        map.put(ft.LOGIN_WITH_PHONE, "Logg på med PIN");
        map.put(ft.ONE_MOMENT, "Et øyeblikk …");
        map.put(ft.PAY_FAILED_ALERT_TITLE, "Betaling mislyktes");
        map.put(ft.SCAN_CARD_ICON_DESCRIPTION, "Skann");
        map.put(ft.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Feil sikkerhetskode. Prøv på nytt.");
        map.put(ft.VIA_LABEL, "via");
        map.put(ft.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Systemfeil. Prøv på nytt senere.");
        Map map2 = f21489b;
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Del informasjon om <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Del informasjon med dem om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Del <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Del <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Del informasjon om <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Del informasjon om <a href='%1$s'>finansieringskildene</a> som er tilknyttet PayPal-kontoen din.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Del informasjon om <a href='%1$s'>betalingsmetodene</a> som er tilknyttet PayPal-kontoen din.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Del <a href='%1$s'>finansieringskildene</a> på vegne av deg inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp hos %2$s via PayPal. Du ber PayPal om å betale alle summer som %3$s ber om.</p><p>Du finner mer informasjon i <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>PayPals avtale om regelmessige betalinger og fakturering</a>.</p>");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp hos %2$s via PayPal. Du ber PayPal om å betale alle summer som %3$s ber om.</p><p>Du finner mer informasjon i <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>PayPals avtale om regelmessige betalinger og fakturering</a>.</p>");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp via PayPal. Du gir PayPal din godkjenning, og ber oss om å betale alle beløp.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp via PayPal. Du gir PayPal din godkjenning, og ber oss om å betale alle beløp.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>Godkjenn betalinger</a> for fremtidige kjøp via PayPal. Du gir PayPal din godkjenning, og ber oss om å betale alle beløp.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Forhåndsgodkjenn fremtidige betalinger fra PayPal-kontoen din uten å logge på PayPal hver gang. <a href='%1$s'>Se ytterligere vilkår</a>, inkludert betalingsmetoder og hvordan du kan avbryte fremtidige betalinger.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Gi %2$s tillatelse til å <a href='%1$s'>be om penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Gi %2$s tillatelse til å <a href='%1$s'>overføre penger</a> på dine vegne inntil du trekker tilbake tillatelsen.");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun informasjon om hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun informasjon om hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun informasjon om hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Betalingsmetoder</strong></h1><p>PayPal deler kun hvilke av finansieringskildene dine som er tilgjengelige for bruk.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Din standard betalingsmetode (PayPal-saldo, tilknyttet bankkonto eller betalingskort, i denne rekkefølgen) brukes til å betale for PayPal-kjøp. Vær oppmerksom på at hvis den standard betalingsmetoden din ikke har nok penger til å dekke kjøpet, kan banken eller kortleverandøren belaste deg et gebyr.</p><p>For å avbryte denne avtalen må du logge på PayPal-kontoen din og gå til <strong>Profil</strong>, så klikker du på <strong>Mine innstillinger</strong> og <strong>Endre</strong> ved siden av ‘Logg på med PayPal’.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>PayPal-saldoen din eller det primære betalingskortet ditt brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne avtalen, logger du på PayPal-kontoen, går til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne avtalen, logger du på PayPal-kontoen, går til <strong>Profil</strong> &gt; <strong>Innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Den standard finansieringskilden din brukes til å utføre fremtidige PayPal-betalinger hos denne forhandleren.</p><p>Hvis du vil avslutte denne avtalen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Regelmessig betaling-delen av <a href='%s'>PayPals brukeravtale</a> er gjeldende.</p><p>For å kontrollere at betalinger fungerer med PayPal-kontoen din, kan denne appen simulere en liten prøvetransaksjonen, men ingen penger overføres.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne godkjenningen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se ‘Forhåndsgodkjente betalinger’-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne godkjenningen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se «Forhåndsgodkjente betalinger»-delen i <a href='%s'>PayPals brukeravtale</a> for å få mer informasjon.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>PayPal-saldoen din eller det primære betalingskortet ditt brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne avtalen, logger du på PayPal-kontoen, går til <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne godkjenningen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se ‘Forhåndsgodkjente betalinger’-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne godkjenningen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se ‘Forhåndsgodkjente betalinger’-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Godkjenning av fremtidige betalinger</strong></h1><p>For å kontrollere at PayPal-kontoen din kan belastes i fremtiden, kan denne appen simulere en liten prøvetransaksjon, men ingen penger overføres.</p><p>Betalingsmetoden du angir som standard brukes til å betale for PayPal-kjøp.</p><p>Hvis du vil avbryte denne godkjenningen, logger du på PayPal-kontoen din, går til <strong>Profil</strong> &gt; <strong>Mine kontoinnstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Se ‘Forhåndsgodkjente betalinger’-delen i <a href='%s'>PayPals brukeravtale</a> for mer informasjon.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Fremtidig betalingsavtale</strong></h1><p>Vi forsøker først å betale med PayPal-saldoen din. Hvis det ikke er nok penger på den, forsøker vi å bruke bankkontoen din, PayPal Credit, betalingskort og/eller eCheck, i den viste rekkefølgen.</p><p>Hvis du vil avbryte denne avtalen, går du til www.paypal.com <strong>Profil</strong> &gt; <strong>Mine innstillinger</strong> &gt; <strong>Logg på med PayPal</strong> og fjerner denne forhandleren fra listen.</p><p>Det kan være nødvendig med en liten betalingsgodkjenning for å kontrollere at PayPal-kontoen din kan belastes i fremtiden. Godkjenningen blir avbrutt, og du belastes ikke.</p>");
        map2.put("LOG_IN_TO_PAYPAL|AU", "Logg på med PayPal");
        map2.put("LOG_IN_TO_PAYPAL|GB", "Logg på med PayPal");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din og klikker på tannhjulikonet. Gå til <strong>Sikkerhet</strong>, velg <strong>Logg på med PayPal</strong> og fjern denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene, og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din og klikker på tannhjulikonet. Gå til <strong>Sikkerhet</strong>, velg <strong>Logg på med PayPal</strong> og fjern denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din og klikker på tannhjulikonet. Gå til <strong>Sikkerhet</strong>, velg <strong>Logg på med PayPal</strong> og fjern denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, klikker på tannhjulikonet øverst til høyre, velger <strong>Sikkerhet</strong>, <strong>Logg på med PayPal</strong> og fjerner forhandleren. Hvis du fortsatt bruker den tidligere versjonen av nettstedet, går du til <strong>Min profil</strong>, velger <strong>Mine kontoinnstillinger</strong>, <strong>Logg på med PayPal</strong> og fjerner forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Profil</strong>-innstillingene, <strong>Logg på med PayPal</strong> og fjerner denne partneren.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.it, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene, og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene, og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med partneren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.ru, klikker på tannhjulikonet øverst til høyre, velger <strong>Sikkerhet</strong>-fanen og fjerner denne partneren under alternativet <strong>Logg på med PayPal</strong>.</p><p>PayPal er ikke ansvarlig for partnerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på PayPal-kontoen din, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.tr, klikker på tannhjulikonet øverst til høyre, velger <strong>Sikkerhet</strong>-fanen og fjerner denne partneren under alternativet <strong>Logg på med PayPal</strong>.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Logg på med PayPal</strong>-alternativene under <strong>Profil</strong>-innstillingene og fjerner denne forhandleren.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Alle relevante transaksjonsdetaljer deles med forhandleren.</p><p>Hvis du vil trekke tilbake tillatelsen din, logger du på paypal.com, går til <strong>Profil</strong>, <strong>Sikkerhet</strong>, finner <strong>Logg på med PayPal</strong> og fjerner denne forhandleren.</p><p>PayPal er ikke ansvarlig for forhandlerens handlinger eller feil.</p>");
        Map map3 = f21490c;
        map3.put("AMOUNT_MISMATCH", "Totalbeløpet for varene i handlekurven samsvarer ikke med kjøpesummen.");
        map3.put("AUTHORIZATION_ALREADY_COMPLETED", "Denne godkjenningen er allerede fullført.");
        map3.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Godkjenningen er i et stadium som ikke kan bli annullert.");
        map3.put("AUTHORIZATION_EXPIRED", "Godkjenning utløpt.");
        map3.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Den forespurte godkjennings-IDen finnes ikke.");
        map3.put("AUTHORIZATION_VOIDED", "Godkjenningen din er annullert.");
        map3.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Kan bare godkjenne den opprinnelige godkjenningen, ikke en ny godkjenning.");
        map3.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Ny godkjenning er ikke tillatt innenfor prøveperioden.");
        map3.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Beløpet overskrider den tillatte grensen.");
        map3.put("CARD_TOKEN_PAYER_MISMATCH", "Får ikke tilgang til lagret kortinformasjonen.");
        map3.put("CREDIT_CARD_CVV_CHECK_FAILED", "Kortopplysningene er ugyldige. Vi ber deg korrigere og sende inn på nytt.");
        map3.put("CREDIT_CARD_REFUSED", "Kortet ble avvist.");
        map3.put("CURRENCY_MISMATCH", "Valuta for innhentingen må være lik valutaen for godkjenning.");
        map3.put("CURRENCY_NOT_ALLOWED", "Denne valutaen støttes for øyeblikket ikke av PayPal.");
        map3.put("DATA_RETRIEVAL", "Systemfeil. Prøv på nytt senere.");
        map3.put("DUPLICATE_REQUEST_ID", "Systemfeil. Prøv på nytt senere.");
        map3.put("EXPIRED_CREDIT_CARD", "Kortet er utløpt");
        map3.put("EXPIRED_CREDIT_CARD_TOKEN", "Informasjonen for dette kortet er ikke lenger registrert.\nVennligst send på nytt.");
        map3.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funksjonen støttes ikke for denne forhandleren.");
        map3.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Denne transaksjonen er allerede delvis refundert.");
        map3.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Øyeblikkelig betaling støttes ikke for den forespurte tjenesten.");
        map3.put("INSTRUMENT_DECLINED", "Den betalingsmetoden du valgte ble ikke godtatt. Velg en annen betalingsmetode.");
        map3.put("INSUFFICIENT_FUNDS", "Kjøperen kan ikke betale – ikke nok penger.");
        map3.put("INTERNAL_SERVICE_ERROR", "Systemfeil. Prøv på nytt senere.");
        map3.put("INVALID_ACCOUNT_NUMBER", "Det kontonummeret finnes ikke.");
        map3.put("INVALID_ARGUMENT", "Transaksjon avvist på grunn av et ugyldig parameter");
        map3.put("INVALID_CITY_STATE_ZIP", "Ugyldig kombinasjon for poststed/land/postnummerkombinasjon.");
        map3.put("INVALID_FACILITATOR_CONFIGURATION", "Denne transaksjonen kan ikke behandles på grunn av en ugyldig systeminnretningskonfigurasjon.");
        map3.put("INVALID_PAYER_ID", "Systemfeil (ugyldig betaler-id). Prøv på nytt senere.");
        map3.put("INVALID_RESOURCE_ID", "Systemfeil. Prøv på nytt senere.");
        map3.put("PAYEE_ACCOUNT_INVALID", "Kontoen til betalingsmottakeren din har ikke en bekreftet e-post.");
        map3.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Selgeren kan for øyeblikket ikke motta betalinger.");
        map3.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Kontoen til betalingsmottakeren din har ikke en bekreftet e-post.");
        map3.put("PAYEE_ACCOUNT_RESTRICTED", "Selgeren kan for øyeblikket ikke motta betalinger.");
        map3.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Kontoen din er låst eller avsluttet.");
        map3.put("PAYER_ACCOUNT_RESTRICTED", "Kontoen din er begrenset.");
        map3.put("PAYER_CANNOT_PAY", "Du kan ikke betale for denne transaksjonen med PayPal.");
        map3.put("PAYER_EMPTY_BILLING_ADDRESS", "Det er nødvendig med en faktureringsadresse ved betalingskorttransaksjoner utenfor PayPal.");
        map3.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Får ikke tilgang til lagret kortinformasjonen.");
        map3.put("PAYMENT_APPROVAL_EXPIRED", "Betalingsgodkjenningen er utløpt.");
        map3.put("PAYMENT_EXPIRED", "Betalingen er utløpt.");
        map3.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Betaleren har ikke godtatt betalingen.");
        map3.put("PAYMENT_REQUEST_ID_INVALID", "PayPal-forespørselen er ugyldig. Prøv på nytt senere.");
        map3.put("PAYMENT_STATE_INVALID", "Denne forespørselen er ugyldig på grunn av gjeldende status for betalingen.");
        map3.put("PERMISSION_DENIED", "Ingen tillatelse til den forespurte operasjonen.");
        map3.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Den forespurte refusjonen overskrider beløpet for den opprinnelige transaksjonen.");
        map3.put("REFUND_TIME_LIMIT_EXCEEDED", "Denne transaksjonen er for gammel til at den kan refunderes.");
        map3.put("REQUIRED_SCOPE_MISSING", "Systemfeil. Prøv på nytt senere.");
        map3.put("TOO_MANY_REAUTHORIZATIONS", "Ingen flere nye godkjenninger er tillatt for denne godkjenningen.");
        map3.put("TRANSACTION_ALREADY_REFUNDED", "Denne transaksjonen er allerede refundert.");
        map3.put("TRANSACTION_LIMIT_EXCEEDED", "Beløpet overskrider den tillatte grensen.");
        map3.put("TRANSACTION_REFUSED", "Transaksjonen ble avvist.");
        map3.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Transaksjonen ble avvist.");
        map3.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Forhandlerprofilen er innstilt til å automatisk tilbakevise visse transaksjoner.");
        map3.put("UNKNOWN_ERROR", "Systemfeil. Prøv på nytt senere.");
        map3.put("UNSUPPORTED_PAYEE_COUNTRY", "Landet støttes ikke.");
        map3.put("VALIDATION_ERROR", "Betalingsinformasjonen er ugyldig. Vi ber deg korrigere og sende inn på nytt.");
        map3.put("ORDER_ALREADY_COMPLETED", "Bestillingen er allerede annullert, utløpt eller fullført.");
        map3.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Maksimalt antall tillatte godkjenninger for bestillingen er nådd.");
        map3.put("ORDER_VOIDED", "Bestillingen er blitt annullert.");
        map3.put("ORDER_CANNOT_BE_VOIDED", "Det er ikke mulig å annullere bestillingen i denne delen av prosessen.");
        map3.put("INVALID_EXPERIENCE_PROFILE_ID", "Systemfeil. Prøv på nytt senere.");
        map3.put("UNAUTHORIZED_PAYMENT", "Forhandleren godtar ikke betalinger av denne typen.");
        map3.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Valuta ikke støttet for korttypen.");
        map3.put("DCC_CC_TYPE_NOT_SUPPORTED", "Korttypen støttes ikke.");
        map3.put("ADDRESS_ADDITION_ERROR", "Det oppstod et problem i løpet av prosessen med å legge til en forsendelsesadresse i PayPal-kontoen.");
        map3.put("DUPLICATE_TRANSACTION", "Duplikattransaksjon.");
        map3.put("INVALID_SHIPPING_ADDRESS", "Den oppgitte leveringsadressen er ikke gyldig.");
        map3.put("PAYMENT_CREATION_ERROR", "Det oppsto et problem med opprettelsen av denne betalingen. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        map3.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Det oppsto et problem med opprettelsen av denne betalingen – kortet ditt er utløpt. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        map3.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Det oppsto et problem med opprettelsen av denne betalingen – direktebetaling kreves, f.eks. med et kredittkort. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Det oppsto et problem med opprettelsen av denne betalingen – kortet må bekreftes. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Det oppsto et problem med opprettelsen av denne betalingen – denne appen krever at kontoen din inneholder et telefonnummer. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Det oppsto et problem med opprettelsen av denne betalingen – kontoen må ha en gyldig finansieringskilde, f.eks. en bankkonto eller et betalingskort. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        map3.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Det oppsto et problem med opprettelsen av denne betalingen – saldoen din er i minus. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        map3.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Det oppsto et problem med opprettelsen av denne betalingen – sendegrensen din er nådd. Gå til PayPal-nettstedet for å kontrollere kontoen din.");
        map3.put("AUTH_RC_RISK_FAILURE", "Avvist grunnet risiko.");
        map3.put("AUTH_RC_OFAC_BLOCKED_IP", "Klienten er ikke godkjent.");
        map3.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klienten er ikke godkjent.");
        map3.put("invalid_user", "Feil brukernavn/passord. Prøv på nytt.");
        map3.put("locked_user", "PayPal-kontoen din er midlertidig sperret. Prøv på nytt senere, eller gå til www.paypal.com for å låse opp PayPal-kontoen din med en gang.");
        map3.put("max_attempts_exceeded", "For mange mislykkede påloggingsforsøk. Prøv på nytt senere.");
        map3.put("invalid_request", "Det har oppstått en feil.");
        map3.put("unauthorized_client", "Ikke godkjent forespørsel.");
        map3.put("access_denied", "Ikke godkjent forespørsel.");
        map3.put("unsupported_response_type", "Det har oppstått en feil.");
        map3.put("invalid_scope", "Ikke godkjent forespørsel.");
        map3.put("server_error", "Systemfeil. Prøv på nytt senere.");
        map3.put("temporarily_unavailable", "Systemfeil. Prøv på nytt senere.");
        map3.put("stepup_required", "Det er ikke mulig å logge på akkurat nå. Prøv på nytt senere, eller gå til www.paypal.com for å løse eventuelle sikkerhetsproblemer med kontoen din.");
        map3.put("account_locked_generate_challenge_limit_exceeded", "For mange påloggingsforsøk. Prøv på nytt senere, eller ta kontakt med PayPal for å få hjelp.");
    }

    @Override // com.paypal.android.sdk.y4
    public final String a() {
        return "nb";
    }

    @Override // com.paypal.android.sdk.y4
    public final /* synthetic */ String a(Enum r32, String str) {
        ft ftVar = (ft) r32;
        String str2 = ftVar.toString() + "|" + str;
        Map map = f21489b;
        return (String) (map.containsKey(str2) ? map.get(str2) : f21488a.get(ftVar));
    }

    @Override // com.paypal.android.sdk.y4
    public final String a(String str) {
        return (String) f21490c.get(str);
    }
}
