package com.paypal.android.sdk;

import java.util.HashMap;
import java.util.Map;
/* loaded from: classes2.dex */
public final class q5 implements y4 {

    /* renamed from: a  reason: collision with root package name */
    private static final Map f21870a = new HashMap();

    /* renamed from: b  reason: collision with root package name */
    private static final Map f21871b = new HashMap();

    /* renamed from: c  reason: collision with root package name */
    private static final Map f21872c = new HashMap();

    public q5() {
        Map map = f21870a;
        map.put(ft.AGREE_AND_PAY, "Zgadzam się i chcę zapłacić");
        map.put(ft.AND_OTHER_FUNDING_SOURCES, "i inne");
        map.put(ft.AUTHENTICATING, "Uwierzytelnianie");
        map.put(ft.BACK_BUTTON, "Wstecz");
        map.put(ft.BACKUP_FUNDING_SOURCE, "Rezerwowe");
        map.put(ft.CANCEL, "Anuluj");
        map.put(ft.CARDTYPE_AMERICANEXPRESS, "American Express");
        map.put(ft.CARDTYPE_CARTAAURA, "Carta Aura");
        map.put(ft.CARDTYPE_CARTEAURORE, "Carte Aurore");
        map.put(ft.CARDTYPE_CARTAPREPAGATAPAYPAL, "Carta Prepagata PayPal");
        map.put(ft.CARDTYPE_CARTEBLEUE, "Carte Bancaire");
        map.put(ft.CARDTYPE_COFINOGA, "Cofinoga");
        map.put(ft.CARDTYPE_DELTA, "Delta");
        map.put(ft.CARDTYPE_DISCOVER, "Discover");
        map.put(ft.CARDTYPE_ELECTRON, "Electron");
        map.put(ft.CARDTYPE_JCB, "JCB");
        map.put(ft.CARDTYPE_MAESTRO, "Maestro");
        map.put(ft.CARDTYPE_MASTERCARD, "MasterCard");
        map.put(ft.CARDTYPE_POSTEPAY, "Postepay");
        map.put(ft.CARDTYPE_4ETOILES, "4 étoiles");
        map.put(ft.CARDTYPE_TARJETAAURORA, "Tarjeta Aurora");
        map.put(ft.CARDTYPE_VISA, "Visa");
        map.put(ft.CHANGE_PAYMENT_METHOD, "Zmień formę płatności");
        map.put(ft.CHECKING_ACCOUNT_FOR_INSTITUTION, "Rozliczeniowy");
        map.put(ft.CHECKING_DEVICE, "Sprawdzanie urządzenia…");
        map.put(ft.CLEAR_CREDIT_CARD_INFO, "Wyczyść informacje o karcie");
        map.put(ft.CONFIRM, "Potwierdź");
        map.put(ft.CONFIRM_CLEAR_CREDIT_CARD_INFO, "Na pewno chcesz wyczyścić informacje o karcie?");
        map.put(ft.CONFIRM_CHARGE_CREDIT_CARD, "Obciąż kartę");
        map.put(ft.CONFIRM_LOG_OUT, "Na pewno chcesz się wylogować z serwisu PayPal?");
        map.put(ft.CONFIRM_SEND_PAYMENT, "Zapłać");
        map.put(ft.CONSENT_AGREEMENT_AGREE, "Zgadzam się");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_CREATION_DATE, "Data założenia konta");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_STATUS, "Status konta");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ACCOUNT_TYPE, "Typ rachunku");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_ADDRESS, "Adres");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_AGE_RANGE, "Grupa wiekowa");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_DATE_OF_BIRTH, "Data urodzenia");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_EMAIL_ADDRESS, "Adres e-mail");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_FULL_NAME, "Pełne imię i nazwisko");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_GENDER, "Płeć");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_LANGUAGE, "Język");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_LOCALE, "Lokalizacja");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_PHONE, "Telefon");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTE_TIME_ZONE, "Strefa czasowa");
        map.put(ft.CONSENT_AGREEMENT_ATTRIBUTES, "Udostępnij następujące informacje: %s.");
        map.put(ft.CONSENT_AGREEMENT_EXPRESS_CHECKOUT, "Korzystaj z ekspresowej realizacji transakcji.");
        map.put(ft.CONSENT_AGREEMENT_INTRO, "%s prosi o:");
        map.put(ft.CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS, "Udostępnij <a href='%1$s'>formy płatności</a> powiązane z Twoim kontem PayPal.");
        map.put(ft.CONSENT_AGREEMENT_FUNDING_OPTIONS, "Włącz wyświetlanie opcji finansowania płatności, aby móc dokonać wyboru.");
        map.put(ft.CONSENT_AGREEMENT_FUTURE_PAYMENTS, "<a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy u handlowca %2$s zapłacone w systemie PayPal. Wszystkie kwoty, których zażąda handlowiec %3$s, będą wypłacane przez serwis PayPal na Twoje zlecenie.");
        map.put(ft.CONSENT_AGREEMENT_LOYALTY_CARD, "zgodę na dodawanie kart lojalnościowych i zarządzanie nimi w Twoim portfelu PayPal.");
        map.put(ft.CONSENT_AGREEMENT_MERCHANT_PRIVACY_POLICY, "akceptację warunków określonych w dokumentach %1$s: <a href='%2$s'>zasadach zachowania poufności</a> i <a href='%3$s'>umowie z użytkownikiem</a>");
        map.put(ft.CONSENT_AGREEMENT_REQUEST_MONEY, "Wyraź zgodę na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map.put(ft.CONSENT_AGREEMENT_SEND_MONEY, "Wyraź zgodę na <a href='%1$s'>wysłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map.put(ft.CONSENT_AGREEMENT_TITLE, "Zgoda");
        map.put(ft.EMAIL, "Adres e-mail");
        map.put(ft.ENVIRONMENT_MOCK_DATA, "Dane próbne");
        map.put(ft.ENVIRONMENT_SANDBOX, "Centrum testowe");
        map.put(ft.EXPIRES_ON_DATE, "Wygasa");
        map.put(ft.FINANCIAL_INSTRUMENTS_LEGAL_DETAILS, "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje formy płatności są dostępne do użytku.</p>");
        map.put(ft.FORGOT_PASSWORD, "Nie pamiętasz hasła?");
        map.put(ft.FROM_ACCOUNT, "Od");
        map.put(ft.FUTURE_PAYMENT_METHOD_QUESTION, "Jak chcesz finansować przyszłe płatności na rzecz %1$s?");
        map.put(ft.FUTURE_PAYMENT_LEGAL_DETAILS, "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Do zapłaty za przyszłe zakupy w systemie PayPal u tego handlowca użyte zostanie Twoje domyślne źródło finansowania płatności.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Obowiązują warunki opisane w rozdziale „Płatności cykliczne” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p><p>Aby mieć pewność, że płatności będą pobierane z Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p>");
        map.put(ft.INTERNAL_ERROR, "Błąd wewnętrzny");
        map.put(ft.JAPANESE_COMPLIANCE_AGREEMENT, "<p>Klikając przycisk poniżej, akceptuję postanowienia <a href='%1$s'>Umowy z Użytkownikiem usługi PayPal</a> i oświadczam, że przestrzegam przepisów prawa japońskiego, w tym przepisów dotyczących zakazu dokonywania płatności do Korei Północnej i Iranu zgodnie z <a href='%2$s'>ustawą Foreign Exchange and Foreign Trade Act (Ustawa o wymianie walut i handlu zagranicznym)</a> na potrzeby realizacji tej transakcji.</p>");
        map.put(ft.LOG_IN, "Zaloguj się");
        map.put(ft.LOG_IN_TO_PAYPAL, "Zaloguj się z PayPal");
        map.put(ft.LOG_OUT_BUTTON, "Wyloguj się");
        map.put(ft.LOG_OUT, "Wyloguj się");
        map.put(ft.OK, "OK");
        map.put(ft.PASSWORD, "Hasło");
        map.put(ft.PAY_AFTER_DELIVERY, "Zapłać po dostawie");
        map.put(ft.PAY_WITH, "Zapłać za pomocą");
        map.put(ft.PAY_WITH_CARD, "Zapłać kartą");
        map.put(ft.PAYPAL_BALANCE, "Saldo PayPal");
        map.put(ft.PAYPAL_CREDIT, "Kredyt PayPal");
        map.put(ft.PHONE, "Telefon");
        map.put(ft.PIN, "PIN");
        map.put(ft.PREFERRED_PAYMENT_METHOD, "Preferowana forma płatności");
        map.put(ft.PRIVACY, "Serwis PayPal chroni Twoją <a href='%s'>prywatność</a> i informacje finansowe.");
        map.put(ft.PROCESSING, "Przetwarzanie");
        map.put(ft.REMEMBER_CARD, "Zapamiętaj kartę");
        map.put(ft.REQUEST_MONEY, "Zażądaj zapłaty");
        map.put(ft.REQUEST_OR_SEND_MONEY_LEGAL_DETAILS, "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
        map.put(ft.SAVINGS_ACCOUNT_FOR_INSTITUTION, "Oszczędnościowy");
        map.put(ft.SEND_MONEY, "Wyślij pieniądze");
        map.put(ft.SERVER_PROBLEM, "Wystąpił problem z nawiązaniem połączenia z serwerami PayPal. Spróbuj ponownie.");
        map.put(ft.SESSION_EXPIRED_MESSAGE, "Zaloguj się ponownie do systemu PayPal.");
        map.put(ft.SESSION_EXPIRED_TITLE, "Sesja wygasła");
        map.put(ft.SHIPPING_ADDRESS, "Adres wysyłkowy");
        map.put(ft.SIGN_UP, "Nowy użytkownik? Załóż konto");
        map.put(ft.STAY_LOGGED_IN, "Nie wylogowuj się");
        map.put(ft.SYSTEM_ERROR_WITH_CODE, "Błąd systemu (%s). Spróbuj ponownie później.");
        map.put(ft.TRY_AGAIN, "Spróbuj ponownie");
        map.put(ft.TWO_FA_REQUIRED_ERROR, "Logowanie nie powiodło się, ponieważ dla Twojego konta włączono uwierzytelnianie dwuskładnikowe.");
        map.put(ft.TWO_FACTOR_AUTH_TITLE, "Kod bezpieczeństwa");
        map.put(ft.TWO_FACTOR_AUTH_SUBTITLE, "Wyślij wiadomość tekstową na swój telefon. Otrzymany 6-cyfrowy kod będzie ważny przez 5 minut.");
        map.put(ft.TWO_FACTOR_AUTH_SENDING_DIALOG, "Wysyłanie wiadomości tekstowej");
        map.put(ft.TWO_FACTOR_AUTH_ENTER_SECURITY_CODE, "Podaj 6-cyfrowy kod zabezpieczający");
        map.put(ft.TWO_FACTOR_AUTH_ENTER_MOBILE_NUMBER, "Twój numer telefonu komórkowego");
        map.put(ft.TWO_FACTOR_AUTH_SEND_SMS, "Wyślij wiadomość tekstową");
        map.put(ft.TWO_FACTOR_AUTH_SEND_SMS_AGAIN, "Wyślij wiadomość tekstową ponownie");
        map.put(ft.TWO_FACTOR_AUTH_NO_ACTIVE_TOKENS_ERROR, "Logowanie nie powiodło się, ponieważ dla Twojego konta włączono uwierzytelnianie dwuskładnikowe. Przejdź do witryny PayPal i uaktywnij klucz bezpieczeństwa.");
        map.put(ft.UNAUTHORIZED_DEVICE_MESSAGE, "Dokonywanie płatności z tego urządzenia jest niedozwolone.");
        map.put(ft.UNAUTHORIZED_DEVICE_TITLE, "Nieautoryzowane urządzenie");
        map.put(ft.UNAUTHORIZED_MERCHANT_MESSAGE, "Płatności na rzecz tego handlowca nie są dozwolone (nieprawidłowy identyfikator klienta).");
        map.put(ft.UNAUTHORIZED_MERCHANT_TITLE, "Nieprawidłowy handlowiec");
        map.put(ft.UNEXPECTED_PAYMENT_FLOW, "Wystąpił problem z przetworzeniem płatności. Spróbuj ponownie.");
        map.put(ft.UNKNOWN_FUNDING_SOURCE, "Nierozpoznane źródło");
        map.put(ft.WE_ARE_SORRY, "Przepraszamy.");
        map.put(ft.YOUR_ORDER, "Twoje zamówienie");
        map.put(ft.ANDROID_OS_TOO_OLD, "Urządzenie nie może skomunikować się z PayPal, ponieważ ta wersja systemu Android jest zbyt stara. Zaktualizuj system Android lub skorzystaj z nowszego urządzenia.");
        map.put(ft.CLEAR_CC_ALERT_TITLE, "Usunąć kartę?");
        map.put(ft.CONSENT_FAILED_ALERT_TITLE, "Udzielenie zgody nie powiodło się");
        map.put(ft.CONNECTION_FAILED_TITLE, "Próba połączenia nieudana");
        map.put(ft.LOGIN_FAILED_ALERT_TITLE, "Logowanie nie powiodło się");
        map.put(ft.LOGIN_WITH_EMAIL, "Zaloguj się za pomocą hasła");
        map.put(ft.LOGIN_WITH_PHONE, "Zaloguj się przy użyciu kodu PIN");
        map.put(ft.ONE_MOMENT, "Chwileczkę…");
        map.put(ft.PAY_FAILED_ALERT_TITLE, "Płatność nie powiodła się");
        map.put(ft.SCAN_CARD_ICON_DESCRIPTION, "Skanuj");
        map.put(ft.TWO_FACTOR_AUTH_INVALID_ONE_TIME_PASSWORD, "Nieprawidłowy kod bezpieczeństwa. Spróbuj ponownie.");
        map.put(ft.VIA_LABEL, "przez");
        map.put(ft.PP_SERVICE_ERROR_JSON_PARSE_ERROR, "Błąd systemu. Spróbuj ponownie później.");
        Map map2 = f21871b;
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|AT", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BE", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|BG", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CH", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CY", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|CZ", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DE", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|DK", "Udostępnij informacje o <a href='%1$s'>formach płatności</a> powiązanych z Twoim kontem PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|EE", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|ES", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|FI", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GB", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> powiązane z Twoim kontem PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|GR", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|HU", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IE", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|IT", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> powiązane z Twoim kontem PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LI", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LT", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LU", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|LV", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|MT", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NL", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|NO", "Udostępnij informacje o <a href='%1$s'>formach płatności</a> powiązanych z Twoim kontem PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PL", "Udostępnij informacje o <a href='%1$s'>źródłach finansowania płatności</a> powiązanych z Twoim kontem PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|PT", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SE", "Udostępnij informacje o <a href='%1$s'>formach płatności</a> powiązanych z Twoim kontem PayPal.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SI", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SK", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|SM", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FINANCIAL_INSTRUMENTS|VA", "Udostępnij <a href='%1$s'>źródła finansowania płatności</a> w swoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|AU", "<p><a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy u handlowca %2$s zapłacone w systemie PayPal. Wszystkie kwoty, których zażąda handlowiec %3$s, będą wypłacane przez serwis PayPal na Twoje zlecenie.</p><p>Aby uzyskać więcej informacji, zapoznaj się z <a href='https://www.paypal.com/webapps/mpp/ua/recurringpymts-full'>umową o płatnościach cyklicznych i umową rozliczeniową PayPal</a>.</p>");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|CN", "<p><a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy u handlowca %2$s zapłacone w systemie PayPal. Wszystkie kwoty, których zażąda handlowiec %3$s, będą wypłacane przez serwis PayPal na Twoje zlecenie.</p><p>Aby uzyskać więcej informacji, zapoznaj się z <a href='https://cms.paypal.com/c2/cgi-bin/?cmd=_render-content&content_ID=ua/UserAgreement_full'>umową o płatnościach cyklicznych i umową rozliczeniową PayPal</a>.</p>");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|MY", "<a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy zapłacone w systemie PayPal. Zlecasz firmie PayPal wypłacanie wszystkich kwot i udzielasz jej do tego stosownej autoryzacji.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|NZ", "<a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy zapłacone w systemie PayPal. Zlecasz firmie PayPal wypłacanie wszystkich kwot i udzielasz jej do tego stosownej autoryzacji.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|SG", "<a href='%1$s'>autoryzowanie opłat</a> za przyszłe zakupy zapłacone w systemie PayPal. Zlecasz firmie PayPal wypłacanie wszystkich kwot i udzielasz jej do tego stosownej autoryzacji.");
        map2.put("CONSENT_AGREEMENT_FUTURE_PAYMENTS|US", "Wstępnie zatwierdzaj dokonywane z Twojego konta PayPal płatności z datą przyszłą bez konieczności każdorazowego logowania się w systemie PayPal. <a href='%1$s'>Zobacz dodatkowe warunki</a> dotyczące m.in. form płatności i sposobu anulowania płatności z datą przyszłą.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|AT", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|BE", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|CH", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|DE", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|GB", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|NL", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_REQUEST_MONEY|PL", "Zezwól %2$s na <a href='%1$s'>żądanie zapłaty</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|AT", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|BE", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|CH", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|DE", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|GB", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|NL", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("CONSENT_AGREEMENT_SEND_MONEY|PL", "Zezwól %2$s na <a href='%1$s'>wysyłanie pieniędzy</a> w Twoim imieniu. Zgoda ta będzie ważna do czasu jej wycofania.");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|AT", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BE", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|BG", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CH", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CY", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|CZ", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|DE", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|EE", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|ES", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|FI", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|GR", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|HU", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IE", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|IT", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LI", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LT", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LU", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|LV", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|MT", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|NL", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PL", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|PT", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SI", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SK", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|SM", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FINANCIAL_INSTRUMENTS_LEGAL_DETAILS|VA", "<h1><strong>Formy płatności</strong></h1><p>Firma PayPal udostępnia informacje wyłącznie na temat tego, które Twoje źródła finansowania płatności są dostępne do użytku.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|AU", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności (w kolejności: konto PayPal, powiązany rachunek bankowy, karta debetowa lub kredytowa). Pamiętaj, że jeśli w ramach swojej domyślnej formy płatności nie masz wystarczających środków do dokonania płatności za zakupy, Twój bank lub wystawca karty może obciążyć Cię opłatą.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong>, <strong>Moje ustawienia</strong> i opcję <strong>Zmień</strong> dostępną obok pozycji Zaloguj się z PayPal.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|BR", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Płatności za zakupy w systemie PayPal zostaną pobrane z salda Twojego konta PayPal lub podstawowej karty kredytowej albo debetowej.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|CN", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|GB", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Do zapłaty za przyszłe zakupy w systemie PayPal u tego handlowca użyte zostanie Twoje domyślne źródło finansowania płatności.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Obowiązują warunki opisane w rozdziale „Płatności cykliczne” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p><p>Aby mieć pewność, że płatności będą pobierane z Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|HK", "<h1><strong>Autoryzacja płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę autoryzację, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Więcej informacji znajdziesz w rozdziale „Wstępnie zatwierdzone płatności” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|JP", "<h1><strong>Autoryzacja płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę autoryzację, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Więcej informacji znajdziesz w rozdziale „Wstępnie zatwierdzone płatności” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|MX", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Płatności za zakupy w systemie PayPal zostaną pobrane z salda Twojego konta PayPal lub podstawowej karty kredytowej albo debetowej.</p><p>Aby anulować tę umowę, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|MY", "<h1><strong>Autoryzacja płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę autoryzację, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Więcej informacji znajdziesz w rozdziale „Wstępnie zatwierdzone płatności” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|NZ", "<h1><strong>Autoryzacja płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę autoryzację, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Więcej informacji znajdziesz w rozdziale „Wstępnie zatwierdzone płatności” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|SG", "<h1><strong>Autoryzacja płatności z datą przyszłą</strong></h1><p>Aby mieć pewność, że nie wystąpią problemy z obciążeniem Twojego konta PayPal, aplikacja może przeprowadzić transakcję testową o niewielkiej wartości, w wyniku której nie zostaną jednak przelane żadne środki.</p><p>Do zapłaty za zakupy w systemie PayPal użyta zostanie Twoja domyślna forma płatności.</p><p>Aby anulować tę autoryzację, zaloguj się do konta PayPal i wybierz kolejno <strong>Profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Więcej informacji znajdziesz w rozdziale „Wstępnie zatwierdzone płatności” <a href='%s'>Umowy z Użytkownikiem usługi PayPal</a>.</p>");
        map2.put("FUTURE_PAYMENT_LEGAL_DETAILS|US", "<h1><strong>Umowa dotycząca płatności z datą przyszłą</strong></h1><p>W celu realizacji zakupu system PayPal w pierwszej kolejności korzysta ze środków na Twoim koncie PayPal. Jeśli środki te są niewystarczające, wykorzystane zostaną kolejno: rachunek bankowy, PayPal Credit, karta debetowa, karta kredytowa lub czek elektroniczny.</p><p>Aby anulować tę umowę, na stronie www.paypal.pl wybierz kolejno <strong>Profil</strong> &gt; <strong>Moje ustawienia</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń handlowca z listy.</p><p>Autoryzacja płatności o mniejszej wartości może być wymagana w celu sprawdzenia, czy konto PayPal może być obciążane. Taka autoryzacja zostanie jednak unieważniona, a pobranie opłaty anulowane.</p>");
        map2.put("LOG_IN_TO_PAYPAL|AU", "Zaloguj się z PayPal");
        map2.put("LOG_IN_TO_PAYPAL|GB", "Zaloguj się z PayPal");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AD", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AL", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AT", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal i kliknij ikonę ustawień. Na karcie <strong>Bezpieczeństwo</strong> wybierz opcję <strong>Zaloguj się z PayPal</strong> i usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|AU", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BA", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BE", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|BG", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CH", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal i kliknij ikonę ustawień. Na karcie <strong>Bezpieczeństwo</strong> wybierz opcję <strong>Zaloguj się z PayPal</strong> i usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CY", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|CZ", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DE", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal i kliknij ikonę ustawień. Na karcie <strong>Bezpieczeństwo</strong> wybierz opcję <strong>Zaloguj się z PayPal</strong> i usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|DK", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|EE", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ES", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, kliknij ikonę ustawień w prawym górnym rogu, wybierz kartę <strong>Centrum bezpieczeństwa</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca. Jeśli korzystasz z klasycznej strony internetowej, wybierz kolejno <strong>Mój profil</strong> &gt; <strong>Ustawienia mojego konta</strong> &gt; <strong>Zaloguj się z PayPal</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|FI", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GB", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|GR", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HR", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|HU", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IE", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IS", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|IT", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.it, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LI", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LT", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LU", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|LV", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|MT", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NL", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|NO", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PL", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|PT", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RO", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|RU", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione partnerowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.ru, kliknij ikonę ustawień w prawym górnym rogu, wybierz kartę <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie partnera.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SE", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się do swojego konta PayPal, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SI", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SK", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|SM", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|TR", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.com.tr, kliknij ikonę ustawień w prawym górnym rogu, wybierz kartę <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego partnera.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|UA", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|US", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz opcję <strong>Zaloguj się z PayPal</strong> w obszarze <strong>Profil</strong>, a następnie usuń tego handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|VA", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        map2.put("REQUEST_OR_SEND_MONEY_LEGAL_DETAILS|ZA", "<h1><strong>%s</strong></h1><p>Wszelkie stosowne szczegóły transakcji zostaną udostępnione handlowcowi.</p><p>Aby wycofać zgodę, zaloguj się na stronie paypal.pl, wybierz kartę <strong>Profil</strong> &gt; <strong>Bezpieczeństwo</strong> i, korzystając z opcji <strong>Zaloguj się z PayPal</strong>, usuń tego handlowca.</p><p>Firma PayPal nie odpowiada za działania i błędy po stronie handlowca.</p>");
        Map map3 = f21872c;
        map3.put("AMOUNT_MISMATCH", "Suma wszystkich pozycji w koszyku jest niezgodna z kwotą sprzedaży.");
        map3.put("AUTHORIZATION_ALREADY_COMPLETED", "Ta autoryzacja została już zakończona.");
        map3.put("AUTHORIZATION_CANNOT_BE_VOIDED", "Autoryzacji w aktualnym stanie nie można unieważnić.");
        map3.put("AUTHORIZATION_EXPIRED", "Autoryzacja straciła ważność.");
        map3.put("AUTHORIZATION_ID_DOES_NOT_EXIST", "Numer identyfikacyjny żądanej autoryzacji nie istnieje.");
        map3.put("AUTHORIZATION_VOIDED", "Autoryzacja została anulowana.");
        map3.put("CANNOT_REAUTH_CHILD_AUTHORIZATION", "Ponownej autoryzacji można dokonać tylko w ramach pierwotnej autoryzacji.");
        map3.put("CANNOT_REAUTH_INSIDE_HONOR_PERIOD", "Ponowna autoryzacja nie jest dozwolona w okresie honorowania.");
        map3.put("CAPTURE_AMOUNT_LIMIT_EXCEEDED", "Kwota przekracza dopuszczalny limit.");
        map3.put("CARD_TOKEN_PAYER_MISMATCH", "Brak dostępu do zapisanych informacji o karcie.");
        map3.put("CREDIT_CARD_CVV_CHECK_FAILED", "Dane karty są nieprawidłowe. Popraw je i prześlij ponownie.");
        map3.put("CREDIT_CARD_REFUSED", "Karta została odrzucona.");
        map3.put("CURRENCY_MISMATCH", "Waluta pobranych środków musi być jednakowa z walutą autoryzacji.");
        map3.put("CURRENCY_NOT_ALLOWED", "Twoja waluta nie jest aktualnie obsługiwana przez system PayPal.");
        map3.put("DATA_RETRIEVAL", "Błąd systemu. Spróbuj ponownie później.");
        map3.put("DUPLICATE_REQUEST_ID", "Błąd systemu. Spróbuj ponownie później.");
        map3.put("EXPIRED_CREDIT_CARD", "Karta wygasła");
        map3.put("EXPIRED_CREDIT_CARD_TOKEN", "W systemie nie ma już zapisanych informacji o tej karcie.\nPrześlij je ponownie.");
        map3.put("FEATURE_UNSUPPORTED_FOR_PAYEE", "Funkcja nie jest obsługiwana u tego handlowca.");
        map3.put("FULL_REFUND_NOT_ALLOWED_AFTER_PARTIAL_REFUND", "Ta transakcja została już częściowo zwrócona.");
        map3.put("IMMEDIATE_PAY_NOT_SUPPORTED", "Płatność natychmiastowa nie jest obsługiwana w wybranej opcji.");
        map3.put("INSTRUMENT_DECLINED", "Wybrana przez Ciebie forma płatności nie została zaakceptowana. Wybierz inną formę płatności.");
        map3.put("INSUFFICIENT_FUNDS", "Kupujący nie może zapłacić – niewystarczające środki.");
        map3.put("INTERNAL_SERVICE_ERROR", "Błąd systemu. Spróbuj ponownie później.");
        map3.put("INVALID_ACCOUNT_NUMBER", "Ten numer rachunku nie istnieje.");
        map3.put("INVALID_ARGUMENT", "Transakcja odrzucona z powodu nieprawidłowego parametru");
        map3.put("INVALID_CITY_STATE_ZIP", "Nieprawidłowa kombinacja miasta/województwa/kodu pocztowego.");
        map3.put("INVALID_FACILITATOR_CONFIGURATION", "Nie można przetworzyć transakcji. Podana konfiguracja facylitatora jest nieprawidłowa.");
        map3.put("INVALID_PAYER_ID", "Błąd systemu (nieprawidłowy identyfikator płatnika). Spróbuj ponownie później.");
        map3.put("INVALID_RESOURCE_ID", "Błąd systemu. Spróbuj ponownie później.");
        map3.put("PAYEE_ACCOUNT_INVALID", "Handlowiec nie posiada potwierdzonego adresu e-mail.");
        map3.put("PAYEE_ACCOUNT_LOCKED_OR_CLOSED", "Ten dostawca nie może obecnie odbierać płatności.");
        map3.put("PAYEE_ACCOUNT_NO_CONFIRMED_EMAIL", "Handlowiec nie posiada potwierdzonego adresu e-mail.");
        map3.put("PAYEE_ACCOUNT_RESTRICTED", "Ten dostawca nie może obecnie odbierać płatności.");
        map3.put("PAYER_ACCOUNT_LOCKED_OR_CLOSED", "Twoje konto zostało zablokowane lub zamknięte.");
        map3.put("PAYER_ACCOUNT_RESTRICTED", "Dostęp do Twojego konta został ograniczony.");
        map3.put("PAYER_CANNOT_PAY", "Nie możesz zapłacić za tę transakcję z PayPal.");
        map3.put("PAYER_EMPTY_BILLING_ADDRESS", "W przypadku transakcji kartą kredytową poza systemem PayPal wymagany jest adres rozliczeniowy.");
        map3.put("PAYER_ID_MISSING_FOR_CARD_TOKEN", "Brak dostępu do zapisanych informacji o karcie.");
        map3.put("PAYMENT_APPROVAL_EXPIRED", "Zatwierdzenie płatności straciło ważność.");
        map3.put("PAYMENT_EXPIRED", "Płatność straciła ważność.");
        map3.put("PAYMENT_NOT_APPROVED_FOR_EXECUTION", "Płatnik nie zatwierdził płatności.");
        map3.put("PAYMENT_REQUEST_ID_INVALID", "Identyfikator żądania PayPal jest nieprawidłowy. Spróbuj ponownie później.");
        map3.put("PAYMENT_STATE_INVALID", "Żądanie jest nieprawidłowe z uwagi na aktualny status płatności.");
        map3.put("PERMISSION_DENIED", "Brak uprawnień do wykonania żądanej operacji.");
        map3.put("REFUND_EXCEEDED_TRANSACTION_AMOUNT", "Żądana kwota zwrotu pieniędzy przekracza kwotę pierwotnej transakcji.");
        map3.put("REFUND_TIME_LIMIT_EXCEEDED", "Transakcja została dokonana zbyt dawno, aby dokonać zwrotu pieniędzy.");
        map3.put("REQUIRED_SCOPE_MISSING", "Błąd systemu. Spróbuj ponownie później.");
        map3.put("TOO_MANY_REAUTHORIZATIONS", "Nie można dokonać więcej ponownych autoryzacji w ramach tej autoryzacji.");
        map3.put("TRANSACTION_ALREADY_REFUNDED", "Ta transakcja została już zwrócona.");
        map3.put("TRANSACTION_LIMIT_EXCEEDED", "Kwota przekracza dopuszczalny limit.");
        map3.put("TRANSACTION_REFUSED", "Transakcja została odrzucona.");
        map3.put("TRANSACTION_REFUSED_BY_PAYPAL_RISK", "Transakcja została odrzucona.");
        map3.put("TRANSACTION_REFUSED_PAYEE_PREFERENCE", "Preferencje w profilu handlowca ustawione są na automatyczne odrzucanie pewnych transakcji.");
        map3.put("UNKNOWN_ERROR", "Błąd systemu. Spróbuj ponownie później.");
        map3.put("UNSUPPORTED_PAYEE_COUNTRY", "Twój kraj nie jest obsługiwany.");
        map3.put("VALIDATION_ERROR", "Informacje o płatności są nieprawidłowe. Popraw je i prześlij ponownie.");
        map3.put("ORDER_ALREADY_COMPLETED", "Zamówienie zostało już unieważnione, straciło ważność lub zostało zrealizowane.");
        map3.put("MAXIMUM_ALLOWED_AUTHORIZATION_REACHED_FOR_ORDER", "Osiągnięto limit dozwolonych autoryzacji w ramach tego zamówienia.");
        map3.put("ORDER_VOIDED", "Zamówienie zostało unieważnione.");
        map3.put("ORDER_CANNOT_BE_VOIDED", "Obecny status zamówienia uniemożliwia jego unieważnienie.");
        map3.put("INVALID_EXPERIENCE_PROFILE_ID", "Błąd systemu. Spróbuj ponownie później.");
        map3.put("UNAUTHORIZED_PAYMENT", "Handlowiec nie akceptuje płatności tego typu.");
        map3.put("DCC_UNSUPPORTED_CURRENCY_CC_TYPE", "Waluta nie jest obsługiwana przez ten typ karty.");
        map3.put("DCC_CC_TYPE_NOT_SUPPORTED", "Ten typ karty nie jest obsługiwany.");
        map3.put("ADDRESS_ADDITION_ERROR", "Podczas dodawania adresu wysyłkowego do konta PayPal wystąpił błąd.");
        map3.put("DUPLICATE_TRANSACTION", "Transakcja powielona.");
        map3.put("INVALID_SHIPPING_ADDRESS", "Podany adres wysyłkowy jest nieprawidłowy.");
        map3.put("PAYMENT_CREATION_ERROR", "Wystąpił problem z utworzeniem tej płatności. Sprawdź swoje konto w witrynie PayPal.");
        map3.put("PAYMENT_CREATION_ERROR_EXPIRED_PAYMENT_CARD", "Wystąpił problem z utworzeniem tej płatności – Twoja karta wygasła. Sprawdź swoje konto w witrynie PayPal.");
        map3.put("PAYMENT_CREATION_ERROR_INSTANT_PAYMENT_REQUIRED", "Wystąpił problem z utworzeniem tej płatności – wymagana jest płatność błyskawiczna (na przykład kartą kredytową). Sprawdź swoje konto w witrynie PayPal.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_CONFIRMED_CARD", "Wystąpił problem z utworzeniem tej płatności – karta musi zostać potwierdzona. Sprawdź swoje konto w witrynie PayPal.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_PHONE_NUMBER", "Wystąpił problem z utworzeniem tej płatności – ta aplikacja wymaga, aby na Twoim koncie podany został numer telefonu. Sprawdź swoje konto w witrynie PayPal.");
        map3.put("PAYMENT_CREATION_ERROR_NEED_VALID_FUNDING_INSTRUMENT", "Wystąpił problem z utworzeniem tej płatności – konto wymaga podania ważnego źródła finansowania płatności, np. rachunku bankowego lub karty płatniczej. Sprawdź swoje konto w witrynie PayPal.");
        map3.put("PAYMENT_CREATION_ERROR_NEGATIVE_BALANCE", "Wystąpił problem z utworzeniem tej płatności – saldo konta jest ujemne. Sprawdź swoje konto w witrynie PayPal.");
        map3.put("PAYMENT_CREATION_ERROR_SENDING_LIMIT_REACHED", "Wystąpił problem z utworzeniem tej płatności – osiągnięto limit wysyłania. Sprawdź swoje konto w witrynie PayPal.");
        map3.put("AUTH_RC_RISK_FAILURE", "Odrzucono z uwagi na ryzyko.");
        map3.put("AUTH_RC_OFAC_BLOCKED_IP", "Klient nieautoryzowany.");
        map3.put("AUTH_RC_IP_COMPLIANCE_FAILURE", "Klient nieautoryzowany.");
        map3.put("invalid_user", "Nieprawidłowa nazwa użytkownika / hasło. Spróbuj ponownie.");
        map3.put("locked_user", "Twoje konto PayPal zostało tymczasowo zablokowane. Spróbuj ponownie później lub przejdź do witryny www.paypal.pl i odblokuj swoje konto PayPal.");
        map3.put("max_attempts_exceeded", "Zbyt wiele prób logowania zakończyło się niepowodzeniem. Spróbuj ponownie później.");
        map3.put("invalid_request", "Wystąpił błąd.");
        map3.put("unauthorized_client", "Żądanie nieautoryzowane.");
        map3.put("access_denied", "Żądanie nieautoryzowane.");
        map3.put("unsupported_response_type", "Wystąpił błąd.");
        map3.put("invalid_scope", "Żądanie nieautoryzowane.");
        map3.put("server_error", "Błąd systemu. Spróbuj ponownie później.");
        map3.put("temporarily_unavailable", "Błąd systemu. Spróbuj ponownie później.");
        map3.put("stepup_required", "W tej chwili nie możesz się zalogować. Spróbuj ponownie później lub przejdź do witryny www.paypal.pl i odpowiedz na wątpliwości dotyczące bezpieczeństwa Twojego konta PayPal.");
        map3.put("account_locked_generate_challenge_limit_exceeded", "Zbyt wiele prób logowania. Spróbuj ponownie później lub skontaktuj się z PayPal, aby uzyskać pomoc.");
    }

    @Override // com.paypal.android.sdk.y4
    public final String a() {
        return "pl";
    }

    @Override // com.paypal.android.sdk.y4
    public final /* synthetic */ String a(Enum r32, String str) {
        ft ftVar = (ft) r32;
        String str2 = ftVar.toString() + "|" + str;
        Map map = f21871b;
        return (String) (map.containsKey(str2) ? map.get(str2) : f21870a.get(ftVar));
    }

    @Override // com.paypal.android.sdk.y4
    public final String a(String str) {
        return (String) f21872c.get(str);
    }
}
